(()=>{
const $=s=>document.querySelector(s),fam=m=>window.NFL_CONFIDENCE?.family?.(m)||m.type||'other';let filter='all',game='all',slip=[],lastSig='';
function safeGames(){try{return state.games||[]}catch{return[]}}
function candidates(){try{return window.NFL_PROP_CAROUSEL?.candidates?.()||[]}catch{return[]}}
function mount(){if($('#qolCommand'))return;const nav=$('.mode-tabs');if(!nav)return;const el=document.createElement('section');el.id='qolCommand';el.className='qol-command';el.innerHTML=`<div class="qol-row"><div><span>SLATE</span><h2>Today's board</h2></div><select id="qolDate"><option value="">All upcoming</option></select></div><div class="qol-presets"><button data-preset="bankroll">Bankroll</button><button class="active" data-preset="balanced">Balanced</button><button data-preset="longshot">Longshot</button></div><div class="qol-filters"><select id="qolGame"><option value="all">All games</option></select><div id="qolFamilies"><button class="active" data-family="all">All</button><button data-family="passing">Pass</button><button data-family="rushing">Rush</button><button data-family="receiving">Rec</button><button data-family="receptions">Receptions</button><button data-family="attempts">Attempts</button><button data-family="td">TD</button></div></div><details class="qol-market-best"><summary>Best available by market</summary><div id="qolMarketBest"></div></details>`;nav.parentNode.insertBefore(el,nav);sync(true);wire();renderBest()}
function dateOf(g){const t=new Date(g?.commence_time||0);return Number.isNaN(t.getTime())?'':t.toISOString().slice(0,10)}
function sync(force=false){const ds=$('#qolDate'),gs=$('#qolGame');if(!ds||!gs)return;const games=safeGames(),sig=games.map(g=>`${g.id}:${g.commence_time}`).join('|');if(!force&&sig===lastSig)return;lastSig=sig;const dv=ds.value,gv=gs.value,dates=[...new Set(games.map(dateOf).filter(Boolean))].sort();ds.innerHTML='<option value="">All upcoming</option>'+dates.map(d=>`<option value="${d}">${new Date(d+'T12:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</option>`).join('');if(dates.includes(dv))ds.value=dv;gs.innerHTML='<option value="all">All games</option>'+games.map(g=>`<option value="${g.id}">${g.away} @ ${g.home}</option>`).join('');if(games.some(g=>g.id===gv))gs.value=gv;game=gs.value||'all'}
function familyMatch(m){const f=fam(m).toLowerCase();if(filter==='all')return true;if(filter==='passing')return f.includes('pass')||f.includes('completion');if(filter==='rushing')return f.includes('rush');if(filter==='receiving')return f.includes('receiving');if(filter==='receptions')return f==='receptions';if(filter==='attempts')return f.includes('attempt');if(filter==='td')return f.includes('td')||f.includes('touchdown');return true}
function filtered(){const d=$('#qolDate')?.value,games=safeGames();return candidates().filter(m=>familyMatch(m)&&(game==='all'||m.gameId===game)&&(!d||dateOf(games.find(g=>g.id===m.gameId))===d))}
function renderBest(){const h=$('#qolMarketBest');if(!h)return;const map=new Map();for(const m of filtered()){const f=fam(m);if(!map.has(f))map.set(f,m)}h.innerHTML=[...map].slice(0,8).map(([f,m])=>`<div class="market-best"><span>${f}</span><b>${m.name}</b><small>${window.NFL_CONFIDENCE?.score?.(m)||'—'} confidence</small></div>`).join('')||'<p>No qualified markets for these filters.</p>'}
function applyPreset(p){const r=$('#riskRange'),l=$('#legsSelect');if(!r||!l)return;const cfg=p==='bankroll'?[20,'2']:p==='longshot'?[78,'4']:[45,'3'];r.value=cfg[0];l.value=cfg[1];r.dispatchEvent(new Event('input',{bubbles:true}));l.dispatchEvent(new Event('change',{bubbles:true}));document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===p))}
function addSlip(m,kind){if(!m)return;const id=[m.gameId,m.player||m.team,m.marketKey,m.side,m.point].join('|');if(slip.some(x=>x.id===id))return;slip.push({id,m,kind});renderSlip()}
function conflict(a,b){return a.gameId===b.gameId&&a.player&&a.player===b.player&&fam(a)===fam(b)&&a.side!==b.side}
function quality(){if(!slip.length)return 0;let q=slip.reduce((s,x)=>s+(window.NFL_CONFIDENCE?.score?.(x.m)||0),0)/slip.length;for(let i=0;i<slip.length;i++)for(let j=i+1;j<slip.length;j++)if(conflict(slip[i].m,slip[j].m))q-=15;return Math.max(0,Math.round(q))}
function renderSlip(){let s=$('#qolSlip');if(!s){s=document.createElement('div');s.id='qolSlip';s.className='qol-slip';document.body.appendChild(s)}if(!slip.length){s.classList.remove('open');return}const bad=slip.some((x,i)=>slip.some((y,j)=>j>i&&conflict(x.m,y.m)));s.innerHTML=`<div><b>${slip.length} legs</b><span>Build quality ${quality()}${bad?' • Conflict':''}</span></div><button id="qolClear">Clear</button>`;s.classList.add('open')}
function wire(){const root=$('#qolCommand');root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset)applyPreset(b.dataset.preset);if(b.dataset.family){filter=b.dataset.family;root.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('active',x===b));window.NFL_PROP_CAROUSEL_FILTER={family:filter,game};renderBest();window.NFL_PROP_CAROUSEL?.refresh?.()}});$('#qolGame').addEventListener('change',e=>{game=e.target.value;window.NFL_PROP_CAROUSEL_FILTER={family:filter,game};renderBest();window.NFL_PROP_CAROUSEL?.refresh?.()});$('#qolDate').addEventListener('change',()=>{const v=$('#qolDate').value,sd=$('#slateDate');if(sd&&[...sd.options].some(o=>o.value===v)){sd.value=v;sd.dispatchEvent(new Event('change',{bubbles:true}))}renderBest()});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='qolClear'){slip=[];renderSlip()}if(b.dataset.act==='sgp'||b.dataset.act==='multi'){const k=b.closest('[data-k]')?.dataset.k,m=k&&window.NFL_PROP_CAROUSEL?.find?.(k);addSlip(m,b.dataset.act)}})}
function refresh(){if(!$('#qolCommand'))mount();sync();renderBest()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();setInterval(refresh,1500)},{once:true});else{mount();setInterval(refresh,1500)}window.addEventListener('nfl-qol-rendered',()=>setTimeout(refresh,50));window.addEventListener('nfl-diagnostics-updated',()=>setTimeout(refresh,80));window.NFL_DASHBOARD_QOL={filtered,addSlip,quality,refresh};
})();