(()=>{
const $=s=>document.querySelector(s),all=()=>window.NFL_PROP_CAROUSEL?.candidates?.()||[],fam=m=>window.NFL_CONFIDENCE?.family?.(m)||m.type||'other';let filter='all',game='all',mode='balanced',slip=[];
function mount(){if($('#qolCommand'))return;const nav=$('.mode-tabs');if(!nav)return;const el=document.createElement('section');el.id='qolCommand';el.className='qol-command';el.innerHTML=`<div class="qol-row"><div><span>SLATE</span><h2>Today’s board</h2></div><select id="qolDate"><option value="">All upcoming</option></select></div><div class="qol-presets"><button data-preset="bankroll">Bankroll</button><button class="active" data-preset="balanced">Balanced</button><button data-preset="longshot">Longshot</button></div><div class="qol-filters"><select id="qolGame"><option value="all">All games</option></select><div id="qolFamilies"><button class="active" data-family="all">All</button><button data-family="passing">Pass</button><button data-family="rushing">Rush</button><button data-family="receiving">Rec</button><button data-family="receptions">Receptions</button><button data-family="attempts">Attempts</button><button data-family="td">TD</button></div></div><details class="qol-market-best"><summary>Best available by market</summary><div id="qolMarketBest"></div></details>`;nav.parentNode.insertBefore(el,nav);sync();wire();renderBest()}
function dates(){return[...new Set((state.games||[]).map(g=>new Date(g.commence_time).toISOString().slice(0,10)))].sort()}
function sync(){const ds=$('#qolDate'),gs=$('#qolGame');if(!ds||!gs)return;const old=ds.value;ds.innerHTML='<option value="">All upcoming</option>'+dates().map(d=>`<option value="${d}">${new Date(d+'T12:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</option>`).join('');if(dates().includes(old))ds.value=old;gs.innerHTML='<option value="all">All games</option>'+(state.games||[]).map(g=>`<option value="${g.id}">${g.away} @ ${g.home}</option>`).join('')}
function familyMatch(m){const f=fam(m).toLowerCase();if(filter==='all')return true;if(filter==='passing')return f.includes('pass')||f.includes('completion');if(filter==='rushing')return f.includes('rush');if(filter==='receiving')return f.includes('receiving');if(filter==='receptions')return f==='receptions';if(filter==='attempts')return f.includes('attempt');if(filter==='td')return f.includes('td')||f.includes('touchdown');return true}
function filtered(){const d=$('#qolDate')?.value;return all().filter(m=>familyMatch(m)&&(game==='all'||m.gameId===game)&&(!d||new Date((state.games||[]).find(g=>g.id===m.gameId)?.commence_time||0).toISOString().slice(0,10)===d))}
function renderBest(){const h=$('#qolMarketBest');if(!h)return;const map=new Map();for(const m of filtered()){const f=fam(m);if(!map.has(f))map.set(f,m)}h.innerHTML=[...map].slice(0,8).map(([f,m])=>`<button class="market-best" data-name="${encodeURIComponent(m.name)}"><span>${f}</span><b>${m.name}</b><small>${window.NFL_CONFIDENCE?.score?.(m)||'—'} confidence</small></button>`).join('')||'<p>No qualified markets for these filters.</p>'}
function applyPreset(p){mode=p;const r=$('#riskRange'),l=$('#legsSelect');if(!r||!l)return;if(p==='bankroll'){r.value=20;l.value='2'}else if(p==='balanced'){r.value=45;l.value='3'}else{r.value=78;l.value='4'};r.dispatchEvent(new Event('input',{bubbles:true}));l.dispatchEvent(new Event('change',{bubbles:true}));document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===p))}
function addSlip(m,kind){if(!m)return;const id=[m.gameId,m.player||m.team,m.marketKey,m.side,m.point].join('|');if(slip.some(x=>x.id===id))return;slip.push({id,m,kind});renderSlip()}
function conflict(a,b){if(a.gameId!==b.gameId)return false;if(a.player&&a.player===b.player&&fam(a)===fam(b)&&a.side!==b.side)return true;return false}
function quality(){if(!slip.length)return 0;let q=slip.reduce((s,x)=>s+(window.NFL_CONFIDENCE?.score?.(x.m)||0),0)/slip.length;for(let i=0;i<slip.length;i++)for(let j=i+1;j<slip.length;j++)if(conflict(slip[i].m,slip[j].m))q-=15;return Math.max(0,Math.round(q))}
function renderSlip(){let s=$('#qolSlip');if(!s){s=document.createElement('div');s.id='qolSlip';s.className='qol-slip';document.body.appendChild(s)}if(!slip.length){s.classList.remove('open');return}const bad=slip.some((x,i)=>slip.some((y,j)=>j>i&&conflict(x.m,y.m)));s.innerHTML=`<div><b>${slip.length} legs</b><span>Build quality ${quality()}${bad?' • Conflict':''}</span></div><button id="qolReview">Review</button><button id="qolClear">×</button>`;s.classList.add('open')}
function wire(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset)applyPreset(b.dataset.preset);if(b.dataset.family){filter=b.dataset.family;document.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('active',x===b));window.NFL_PROP_CAROUSEL_FILTER={family:filter,game};renderBest();window.NFL_PROP_CAROUSEL?.refresh?.()}if(b.id==='qolClear'){slip=[];renderSlip()}if(b.dataset.act==='sgp'||b.dataset.act==='multi'){const k=b.closest('[data-k]')?.dataset.k,m=window.NFL_PROP_CAROUSEL?.find?.(k);addSlip(m,b.dataset.act)}});$('#qolGame')?.addEventListener('change',e=>{game=e.target.value;window.NFL_PROP_CAROUSEL_FILTER={family:filter,game};renderBest();window.NFL_PROP_CAROUSEL?.refresh?.()});$('#qolDate')?.addEventListener('change',()=>{const v=$('#qolDate').value,sd=$('#slateDate');if(sd){sd.value=v;sd.dispatchEvent(new Event('change',{bubbles:true}))}renderBest()})}
function improveWhy(){const d=$('#qWhyContent');if(!d)return;const hs=[...d.querySelectorAll('h3')];hs.forEach(h=>{if(h.textContent.includes('Context'))h.textContent='What supports it';if(h.textContent.includes('Why it made'))h.textContent='Why this pick';if(h.textContent.includes('What can'))h.textContent='What could kill it'})}
new MutationObserver(()=>{mount();sync();renderBest();improveWhy()}).observe(document.documentElement,{childList:true,subtree:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();window.NFL_DASHBOARD_QOL={filtered,addSlip,quality};
})();