(()=>{'use strict';
const KEY='sportsDashboardUIV2',sports=['nfl','mlb','ncaaf','ufc','nhl'];
let preferences={};try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))preferences=saved}catch{}
const initialSport=sports.includes(preferences.sport)?preferences.sport:'nfl';
const active=()=>window.__ACTIVE_SPORT||'nfl',results=()=>document.querySelector('#results');
function get(s,key,fallback){const value=preferences[s]?.[key];if(key==='legs')return Number.isInteger(Number(value))&&Number(value)>=2&&Number(value)<=6?Math.min(4,Number(value)):Math.max(2,Math.min(4,Number(fallback)||2));if(key==='markets')return Array.isArray(value)?value.filter(x=>['h2h','spreads','totals','passing','rushing','receiving','receptions','td'].includes(x)):fallback;if(key==='mode')return ['sgp','multi'].includes(value)?value:fallback;return typeof value==='string'?value:fallback}
function put(s,key,value){if(!sports.includes(s))return;preferences[s]={...preferences[s],[key]:key==='legs'?Math.max(2,Math.min(4,Math.floor(Number(value))||2)):value};save()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(preferences))}catch{}}
let sequence=0,pending=null;
function selectSport(s){preferences.sport=s;save();pending=null;window.EXTRA_PICKS?.clear?.();const r=results();if(r){r.style.minHeight=Math.max(220,r.getBoundingClientRect().height)+'px';r.removeAttribute('aria-busy')}document.body.classList.remove('dashboard-updating');requestAnimationFrame(()=>{if(!pending&&active()===s&&r)r.style.minHeight=''});const legs=document.querySelector('#legsSelect');if(legs)legs.value=String(get(s,'legs',s==='nfl'?3:2))}
function placeholder(s){if(active()!==s)return;const r=results();if(!r||r.querySelector('.parlay-card'))return;r.innerHTML='<div class="dashboard-skeleton" role="status" aria-label="Loading '+s.toUpperCase()+' recommendations"><span class="skeleton-heading"></span><span class="skeleton-line"></span><span class="skeleton-line"></span><span class="skeleton-line"></span><span class="skeleton-footer"></span><span class="visually-hidden">Loading '+s.toUpperCase()+' recommendations…</span></div>'}
function begin(s){if(active()!==s)return null;const r=results(),ticket={id:++sequence,sport:s,token:window.__SPORT_TOKEN};pending=ticket;window.EXTRA_PICKS?.clear?.();if(r){r.style.minHeight=Math.max(220,r.getBoundingClientRect().height)+'px';r.setAttribute('aria-busy','true')}document.body.classList.add('dashboard-updating');window.PARLAY_GENERATOR?.syncLabel?.();return ticket}
function end(ticket){if(!ticket||pending!==ticket||active()!==ticket.sport||ticket.token!==window.__SPORT_TOKEN)return;pending=null;requestAnimationFrame(()=>{if(pending||active()!==ticket.sport||ticket.token!==window.__SPORT_TOKEN)return;const r=results();if(r){r.style.minHeight='';r.removeAttribute('aria-busy')}document.body.classList.remove('dashboard-updating');window.TERMINAL_QOL?.enhance?.();window.PARLAY_GENERATOR?.syncLabel?.()})}
function mountControls(){const host=document.querySelector('#parlayControls');if(!host)return;const row=document.createElement('div');row.className='smooth-control-row';document.querySelector('#pickOfDay')?.before(row);for(const selector of ['#nflWeekWrap','#ufcCardWrap','.quality-settings','#mlbLineFilters','#ncaafLineFilters','#nhlMarketFilters']){const node=document.querySelector(selector);if(node)row.append(node)}const leg=document.querySelector('#legsSelect');if(leg)leg.value=String(get(active(),'legs',active()==='nfl'?3:2))}
function mount(){mountControls();document.addEventListener('change',e=>{const s=active(),el=e.target;if(el.id==='legsSelect')put(s,'legs',Number(el.value));if(el.id==='nflWeekSelect')put('nfl','week',el.value);if(el.id==='gameSelect')put('nfl','game',el.value)});document.addEventListener('click',e=>{if(e.target.closest('#marketChips .chip'))put('nfl','markets',[...(window.NFL_PARLAY_STATE?.selectedMarkets||[])]);const mode=e.target.closest('.mode-tabs [data-mode]');if(mode)put('nfl','mode',mode.dataset.mode)});const grid=results();if(grid){grid.setAttribute('tabindex','0');grid.addEventListener('keydown',e=>{if(!grid.classList.contains('nfl-carousel')||e.target!==grid||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const dots=[...document.querySelectorAll('.carousel-dot')];let index=dots.findIndex(b=>b.getAttribute('aria-current')==='true');index=e.key==='Home'?0:e.key==='End'?dots.length-1:Math.max(0,Math.min(dots.length-1,index+(e.key==='ArrowRight'?1:-1)));dots[index]?.click()})}}
window.DASHBOARD_UI={get,put,getSport:()=>initialSport,selectSport,placeholder,begin,end,isUpdating:()=>!!pending&&pending.sport===active()};
document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,0),{once:true});
})();
