(() => {
  const BETS_KEY='nflParlayBets:v2';
  const STATS_URL='https://github.com/nflverse/nflverse-data/releases/download/player_stats/player_stats.csv.gz';
  let statsIndex=new Map(),statsStatus='Loading',lastSig='',renderTimer=null;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const fmtOdds=n=>n>0?'+'+Math.round(n):String(Math.round(n));
  const implied=o=>o<0?(-o)/((-o)+100):100/(o+100);
  const dec=o=>o>0?1+o/100:1+100/(-o);
  const amer=d=>d>=2?Math.round((d-1)*100):Math.round(-100/(d-1));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
  const money=n=>(Number(n)||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
  function liveGames(){try{return (state.games||[]).filter(g=>g?.dataSource==='Polymarket'||(!String(g?.id||'').startsWith('demo-')))}catch{return[]}}
  function isDemoOnly(){const all=(()=>{try{return state.games||[]}catch{return[]}})();return !!all.length && !liveGames().length}
  function marketSource(g,m){return m.source||g.dataSource||(state.apiKey?'Caesars':'Unknown')}
  function normalizeMarket(g,m){return {id:[g.id,m.marketKey||m.type,m.player||m.team,m.side||'',m.point??'',m.price].join('|'),gameId:g.id,game:`${g.away} @ ${g.home}`,away:g.away,home:g.home,type:m.type,marketKey:m.marketKey||m.type,name:m.name,player:m.player||'',team:m.team||'',position:m.position||'',side:m.side||'',point:m.point,price:Number(m.price),source:marketSource(g,m),sourceQuality:Number(m.sourceQuality)||(marketSource(g,m)==='Caesars'?78:60),raw:m};}
  function allMarkets(){return liveGames().flatMap(g=>(g.markets||[]).map(m=>normalizeMarket(g,m))).filter(m=>Number.isFinite(m.price));}
  function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];function row(s){const a=[];let q=false,x='';for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){x+='"';i++}else q=!q}else if(c===','&&!q){a.push(x);x=''}else x+=c}a.push(x);return a}const h=row(lines[0]);return lines.slice(1).map(l=>{const v=row(l),o={};h.forEach((k,i)=>o[k]=v[i]);return o})}
  async function loadStats(){statsStatus='Loading';renderSoon();try{const r=await fetch(STATS_URL);if(!r.ok)throw Error('HTTP '+r.status);let text;const buf=await r.arrayBuffer();try{if('DecompressionStream'in window){const ds=new DecompressionStream('gzip');text=await new Response(new Blob([buf]).stream().pipeThrough(ds)).text()}else throw Error('gzip unsupported')}catch{try{text=new TextDecoder().decode(buf)}catch{throw Error('Unable to decode nflverse stats')}}const rows=parseCSV(text);if(!rows.length)throw Error('No stats rows');const seasons=rows.map(r=>Number(r.season)).filter(Number.isFinite),latest=Math.max(...seasons.filter(s=>s<=new Date().getFullYear()));const use=rows.filter(r=>Number(r.season)>=latest-1&&Number(r.week)>0);for(const r of use){const name=r.player_display_name||r.player_name||r.player||r.name;if(!name)continue;const k=norm(name);if(!statsIndex.has(k))statsIndex.set(k,[]);statsIndex.get(k).push(r)}for(const a of statsIndex.values())a.sort((x,y)=>(Number(x.season)-Number(y.season))||(Number(x.week)-Number(y.week)));statsStatus=`Ready • ${statsIndex.size} players`;window.NFL_DIAGNOSTICS?.add?.({source:'nflverse',url:STATS_URL,status:200,ok:true,count:use.length,note:'player_stats loaded'})}catch(e){statsStatus='Unavailable';window.NFL_DIAGNOSTICS?.add?.({source:'nflverse',url:STATS_URL,status:'ERR',ok:false,error:String(e.message||e)})}renderSoon()}
  const metricMap={player_pass_yds:['passing_yards'],player_pass_tds:['passing_tds'],player_pass_attempts:['attempts','passing_attempts'],player_pass_completions:['completions','passing_completions'],player_rush_yds:['rushing_yards'],player_rush_attempts:['carries','rushing_attempts'],player_reception_yds:['receiving_yards'],player_receptions:['receptions']};
  function val(row,keys){for(const k of keys){const n=Number(row[k]);if(Number.isFinite(n))return n}return null}
  function median(a){if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2}
  function propAnalysis(m){if(!m.player||m.type==='td'||!Number.isFinite(Number(m.point)))return null;const keys=metricMap[m.marketKey];if(!keys)return null;const rows=statsIndex.get(norm(m.player))||[];const values=rows.map(r=>({season:Number(r.season),week:Number(r.week),v:val(r,keys)})).filter(x=>Number.isFinite(x.v));if(values.length<2)return null;const last=values.slice(-5),line=Number(m.point),side=m.side||'over',hits=last.filter(x=>side==='under'?x.v<line:x.v>line).length,hitRate=hits/last.length,avg=last.reduce((s,x)=>s+x.v,0)/last.length,med=median(last.map(x=>x.v)),market=implied(m.price);const sample=Math.min(1,last.length/5),statProb=.5+(hitRate-.5)*sample*.72,model=clamp(market*.45+statProb*.55,.08,.92),edge=model-market;return {n:last.length,hitRate,avg,median:med,model,edge,last:last.map(x=>x.v)} }
  function priceQuality(m){let q=50;if(m.price>=-180&&m.price<=120)q+=14;else if(m.price<-300||m.price>350)q-=16;if(m.source==='Caesars')q+=10;if(m.source==='Polymarket')q+=(m.sourceQuality-50)*.32;return clamp(q,0,100)}
  function evaluate(m){const a=propAnalysis(m),pq=priceQuality(m);let score=pq*.42,confidence=5.1,edge=null;if(a){edge=a.edge;score+=a.model*35+clamp(a.edge*180,-15,20)+a.hitRate*18;confidence=clamp(4.5+a.model*3.4+a.hitRate*1.2+Math.max(0,a.edge)*8,1,9.3)}else{const p=implied(m.price);score+=p*25;confidence=clamp(4.4+p*2+(m.sourceQuality||60)/100,1,7.1)}if(m.player&&a)score+=8;if(m.type==='td')score-=6;return {...m,analysis:a,marketQuality:pq,score,confidence,edge};}
  function candidates(){return allMarkets().map(evaluate).sort((a,b)=>b.score-a.score)}
  function stakePct(conf,parlay=false){let p=conf>=8.5?.015:conf>=7.8?.0125:conf>=7?.01:conf>=6.2?.0075:.004;if(parlay)p=Math.min(.0075,p*.65);return p}
  function bankroll(){return Math.max(0,Number(document.getElementById('currentBankroll')?.value)||0)}
  function combinedOdds(items){return amer(items.reduce((d,x)=>d*dec(x.price),1))}
  function bestBuilder(cs){const out=[];for(const x of cs){if(x.confidence<6.2||x.price<-260||x.price>180)continue;if(out.some(y=>y.gameId===x.gameId))continue;out.push(x);if(out.length===3)break}return out}
  function plusMoney(cs){return cs.find(x=>x.price>100&&x.price<=350&&x.confidence>=6)||null}
  function bestBet(cs){return cs.find(x=>x.analysis&&x.confidence>=6.2)||cs.find(x=>x.confidence>=6.4)||null}
  function bestProp(cs){return cs.find(x=>x.player&&x.analysis&&x.confidence>=6)||cs.find(x=>x.player&&x.confidence>=5.8)||null}
  function metricHTML(x){if(!x)return'';const a=x.analysis;const edge=a?`${a.edge>=0?'+':''}${(a.edge*100).toFixed(1)}%`:'N/A';return `<div class="v2-metrics"><span>Market quality <b>${Math.round(x.marketQuality)}/100</b></span><span>Model edge <b>${edge}</b></span><span>Confidence <b>${x.confidence.toFixed(1)}/10</b></span>${a?`<span>L${a.n} hit <b>${Math.round(a.hitRate*100)}%</b></span>`:''}</div>`}
  function pickCard(title,x){if(!x)return `<article class="v2-card v2-pass"><span class="v2-kicker">${title}</span><h3>PASS</h3><p>No live market cleared the current quality threshold.</p></article>`;const pct=stakePct(x.confidence),amt=bankroll()*pct,a=x.analysis;return `<article class="v2-card"><span class="v2-kicker">${title}</span><div class="v2-title-row"><h3>${x.name}</h3><strong>${fmtOdds(x.price)}</strong></div><p class="v2-game">${x.game} • ${x.source}</p>${metricHTML(x)}${a?`<p class="v2-note">L${a.n}: avg ${a.avg.toFixed(1)}, median ${a.median.toFixed(1)} vs line ${x.point}. Market ${(implied(x.price)*100).toFixed(1)}%, stat-blend model ${(a.model*100).toFixed(1)}%.</p>`:`<p class="v2-note">Market-only lean. Confidence is capped because no independent player-stat projection is available.</p>`}<div class="v2-stake"><span>Suggested stake</span><b>${money(amt)} <small>${(pct*100).toFixed(2)}%</small></b></div></article>`}
  function parlayCard(title,items,tag){if(items.length<2)return `<article class="v2-card v2-pass"><span class="v2-kicker">${title}</span><h3>PASS</h3><p>Not enough independent live edges to build this ticket.</p></article>`;const odds=combinedOdds(items),conf=items.reduce((s,x)=>s+x.confidence,0)/items.length-1.1,pct=stakePct(conf,true),amt=bankroll()*pct;return `<article class="v2-card"><span class="v2-kicker">${title}</span><div class="v2-title-row"><h3>${tag}</h3><strong>${fmtOdds(odds)}</strong></div><div class="v2-ticket">${items.map((x,i)=>`<div><b>${i+1}. ${x.name}</b><span>${x.game} ${fmtOdds(x.price)}</span></div>`).join('')}</div><div class="v2-metrics"><span>Avg confidence <b>${conf.toFixed(1)}/10</b></span><span>Games <b>${items.length}</b></span></div><div class="v2-stake"><span>Suggested stake</span><b>${money(amt)} <small>${(pct*100).toFixed(2)}%</small></b></div></article>`}
  function bets(){try{return JSON.parse(localStorage.getItem(BETS_KEY))||[]}catch{return[]}}
  function saveBets(v){localStorage.setItem(BETS_KEY,JSON.stringify(v))}
  function settle(id,result){const a=bets(),b=a.find(x=>x.id===id);if(!b||b.result!=='pending')return;b.result=result;b.settledAt=Date.now();let delta=0;if(result==='win')delta=b.odds>0?b.stake*b.odds/100:b.stake*100/Math.abs(b.odds);if(result==='loss')delta=-b.stake;const input=document.getElementById('currentBankroll');if(input){input.value=(Math.max(0,(Number(input.value)||0)+delta)).toFixed(2);input.dispatchEvent(new Event('input',{bubbles:true}))}saveBets(a);renderSoon()}
  function addBet(){const sel=document.getElementById('v2BetSelection')?.value.trim(),stake=Number(document.getElementById('v2BetStake')?.value),odds=Number(document.getElementById('v2BetOdds')?.value);if(!sel||!(stake>0)||!Number.isFinite(odds))return;const a=bets();a.unshift({id:crypto.randomUUID?.()||String(Date.now()),selection:sel,stake,odds,result:'pending',createdAt:Date.now()});saveBets(a);renderSoon()}
  function trackerHTML(){const a=bets(),settled=a.filter(x=>x.result!=='pending'),risk=settled.reduce((s,x)=>s+x.stake,0),profit=settled.reduce((s,x)=>s+(x.result==='win'?(x.odds>0?x.stake*x.odds/100:x.stake*100/Math.abs(x.odds)):x.result==='loss'?-x.stake:0),0),wins=settled.filter(x=>x.result==='win').length,losses=settled.filter(x=>x.result==='loss').length;return `<section class="v2-panel"><div class="v2-head"><div><span class="v2-kicker">BANKROLL</span><h2>Bet Tracker</h2></div><div class="v2-summary"><b>${wins}-${losses}</b><span>ROI ${risk?((profit/risk)*100).toFixed(1):'0.0'}% • ${profit>=0?'+':''}${money(profit)}</span></div></div><div class="v2-bet-form"><input id="v2BetSelection" placeholder="Selection"><input id="v2BetStake" type="number" min="0" step=".01" placeholder="Stake"><input id="v2BetOdds" type="number" placeholder="Odds"><button id="v2AddBet">Add bet</button></div><div class="v2-history">${a.slice(0,8).map(b=>`<div class="v2-bet-row"><div><b>${b.selection}</b><span>${money(b.stake)} @ ${fmtOdds(b.odds)}</span></div><div>${b.result==='pending'?`<button data-settle="${b.id}:win">W</button><button data-settle="${b.id}:loss">L</button><button data-settle="${b.id}:push">P</button>`:`<span class="v2-result ${b.result}">${b.result.toUpperCase()}</span>`}</div></div>`).join('')||'<p class="v2-empty">No tracked bets yet.</p>'}</div></section>`}
  function diagnosticsHTML(){const rows=window.NFL_DIAGNOSTICS?.rows?.()||[];return `<section class="v2-panel"><div class="v2-head"><div><span class="v2-kicker">DEVELOPER</span><h2>Live Source Diagnostics</h2></div><button id="v2ClearDiag">Clear</button></div><div class="v2-diag-summary"><span>nflverse <b>${statsStatus}</b></span><span>Requests <b>${rows.length}</b></span></div><div class="v2-diag">${rows.slice(-12).reverse().map(r=>`<div><b class="${r.ok?'ok':'bad'}">${r.source} ${r.status}</b><span>${r.count!==''&&r.count!=null?`${r.count} rows • `:''}${r.ms||0}ms${r.error?' • '+r.error:''}</span><small>${String(r.url||'').replace(location.origin,'')}</small></div>`).join('')||'<p>No diagnostic calls captured yet.</p>'}</div></section>`}
  function render(){const root=document.getElementById('v2Product');if(!root)return;const demo=isDemoOnly(),cs=candidates(),best=bestBet(cs),prop=bestProp(cs),builder=bestBuilder(cs),pm=plusMoney(cs);let plusItems=pm?[pm]:[];if(plusItems.length<2){const two=bestBuilder(cs.filter(x=>x.price>-150)).slice(0,2);if(two.length===2)plusItems=two}root.innerHTML=`<section class="v2-panel v2-dashboard"><div class="v2-head"><div><span class="v2-kicker">DECISION DASHBOARD</span><h2>Today's Board</h2><p>${demo?'Preview only • no live source available':`${liveGames().length} live games • ${cs.length} normalized markets • ${statsStatus}`}</p></div><button id="v2Refresh">Refresh</button></div>${demo?`<div class="v2-blocked"><b>No actionable live data</b><span>Demo markets are disabled for betting recommendations. Open diagnostics to repair the source instead.</span></div>`:`<div class="v2-grid">${pickCard('BEST BET',best)}${pickCard('BEST PLAYER PROP',prop)}${parlayCard('BANKROLL BUILDER',builder.slice(0,Math.max(2,Math.min(3,builder.length))),'2–3 Leg Core')}${plusItems.length===1?pickCard('PLUS-MONEY',plusItems[0]):parlayCard('PLUS-MONEY',plusItems,'Payout Lean')}</div>`}</section>${trackerHTML()}${diagnosticsHTML()}`;
    document.getElementById('v2Refresh')?.addEventListener('click',()=>{window.NFL_POLYMARKET_FALLBACK?.clearCache?.();window.NFL_POLYMARKET_FALLBACK?.load?.();renderSoon()});document.getElementById('v2AddBet')?.addEventListener('click',addBet);document.querySelectorAll('[data-settle]').forEach(b=>b.addEventListener('click',()=>{const [id,r]=b.dataset.settle.split(':');settle(id,r)}));document.getElementById('v2ClearDiag')?.addEventListener('click',()=>{window.NFL_DIAGNOSTICS?.clear?.();renderSoon()});
    const legacy=document.querySelector('.daily-picks-section');if(legacy)legacy.style.display='none';if(demo){const results=document.getElementById('results');if(results)results.innerHTML='<div class="empty">Demo mode is preview-only. Connect a live source before generating actionable recommendations.</div>';const rh=document.getElementById('resultsTitle');if(rh)rh.textContent='No live betting recommendations';}
  }
  function renderSoon(){clearTimeout(renderTimer);renderTimer=setTimeout(render,120)}
  function signature(){try{return (state.games||[]).map(g=>`${g.id}:${g.dataSource||''}:${g.markets?.length||0}`).join('|')+'|'+document.getElementById('dataStatus')?.textContent+'|'+document.getElementById('currentBankroll')?.value}catch{return''}}
  document.addEventListener('DOMContentLoaded',()=>{const anchor=document.querySelector('.mode-tabs');const root=document.createElement('div');root.id='v2Product';anchor?.parentNode.insertBefore(root,anchor);window.addEventListener('nfl-diagnostics-updated',renderSoon);document.getElementById('currentBankroll')?.addEventListener('input',renderSoon);setInterval(()=>{const s=signature();if(s!==lastSig){lastSig=s;renderSoon()}},700);renderSoon();loadStats()});
})();