(() => {
  const BETS_KEY='nflParlayBets:v2';
  let renderTimer=null;
  const money=n=>(Number(n)||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
  const fmtOdds=n=>n>0?'+'+Math.round(n):String(Math.round(n));
  function liveGames(){try{return (state.games||[]).filter(g=>g?.dataSource==='Polymarket'||(!String(g?.id||'').startsWith('demo-')))}catch{return[]}}
  function isDemoOnly(){const a=(()=>{try{return state.games||[]}catch{return[]}})();return !!a.length&&!liveGames().length}
  function bankroll(){return Math.max(0,Number(document.getElementById('currentBankroll')?.value)||0)}
  function implied(o){return o<0?(-o)/((-o)+100):100/(o+100)}
  function normalize(g,m){return {...m,gameId:g.id,game:`${g.away} @ ${g.home}`,source:m.source||g.dataSource||(state.apiKey?'Caesars':'Unknown'),price:Number(m.price),sourceQuality:Number(m.sourceQuality)||60}}
  function candidates(){return liveGames().flatMap(g=>(g.markets||[]).map(m=>normalize(g,m))).filter(x=>Number.isFinite(x.price)).map(x=>{const p=implied(x.price),q=Math.max(0,Math.min(100,50+(x.price>=-180&&x.price<=120?14:0)+(x.source==='Caesars'?10:0)+(x.source==='Polymarket'?(x.sourceQuality-50)*.3:0))),confidence=Math.max(1,Math.min(7.1,4.4+p*2+x.sourceQuality/100));return {...x,marketQuality:q,confidence,score:q*.55+p*35}}).sort((a,b)=>b.score-a.score)}
  function stakePct(c,parlay=false){let p=c>=7?.01:c>=6.2?.0075:.004;return parlay?Math.min(.006,p*.6):p}
  function card(title,x){if(!x)return `<article class="v2-card v2-pass"><span class="v2-kicker">${title}</span><h3>PASS</h3><p>No live market cleared the current threshold.</p></article>`;const pct=stakePct(x.confidence);return `<article class="v2-card"><span class="v2-kicker">${title}</span><div class="v2-title-row"><h3>${x.name}</h3><strong>${fmtOdds(x.price)}</strong></div><p class="v2-game">${x.game} • ${x.source}</p><div class="v2-metrics"><span>Market quality <b>${Math.round(x.marketQuality)}/100</b></span><span>Confidence <b>${x.confidence.toFixed(1)}/10</b></span></div><p class="v2-note">Fast market-only score. Detailed nflverse analysis loads only on demand.</p><div class="v2-stake"><span>Suggested stake</span><b>${money(bankroll()*pct)} <small>${(pct*100).toFixed(2)}%</small></b></div></article>`}
  function bets(){try{return JSON.parse(localStorage.getItem(BETS_KEY))||[]}catch{return[]}}
  function tracker(){const a=bets();return `<section class="v2-panel"><div class="v2-head"><div><span class="v2-kicker">BANKROLL</span><h2>Bet Tracker</h2></div></div><div class="v2-history">${a.slice(0,5).map(b=>`<div class="v2-bet-row"><div><b>${b.selection}</b><span>${money(b.stake)} @ ${fmtOdds(b.odds)}</span></div><span>${b.result||'pending'}</span></div>`).join('')||'<p class="v2-empty">No tracked bets yet.</p>'}</div></section>`}
  function diagnostics(){const rows=window.NFL_DIAGNOSTICS?.rows?.()||[];return `<section class="v2-panel"><div class="v2-head"><div><span class="v2-kicker">DEVELOPER</span><h2>Live Source Diagnostics</h2></div></div><div class="v2-diag">${rows.slice(-6).reverse().map(r=>`<div><b class="${r.ok?'ok':'bad'}">${r.source} ${r.status}</b><span>${r.count??''} ${r.ms||0}ms ${r.error||''}</span></div>`).join('')||'<p>No diagnostic calls captured yet.</p>'}</div></section>`}
  function render(){const root=document.getElementById('v2Product');if(!root)return;const demo=isDemoOnly(),cs=candidates(),best=cs.find(x=>x.confidence>=6.2)||null,prop=cs.find(x=>x.player&&x.confidence>=5.8)||null;root.innerHTML=`<section class="v2-panel v2-dashboard"><div class="v2-head"><div><span class="v2-kicker">DECISION DASHBOARD</span><h2>Today's Board</h2><p>${demo?'Preview only • no live source available':`${liveGames().length} live games • ${cs.length} markets • fast mode`}</p></div><button id="v2Refresh">Refresh</button></div>${demo?'<div class="v2-blocked"><b>No actionable live data</b><span>Demo markets are disabled for betting recommendations.</span></div>':`<div class="v2-grid">${card('BEST BET',best)}${card('BEST PLAYER PROP',prop)}</div>`}</section>${tracker()}${diagnostics()}`;document.getElementById('v2Refresh')?.addEventListener('click',()=>window.NFL_POLYMARKET_FALLBACK?.load?.());const legacy=document.querySelector('.daily-picks-section');if(legacy)legacy.style.display='none';}
  function renderSoon(){clearTimeout(renderTimer);renderTimer=setTimeout(render,80)}
  document.addEventListener('DOMContentLoaded',()=>{const anchor=document.querySelector('.mode-tabs'),root=document.createElement('div');root.id='v2Product';anchor?.parentNode.insertBefore(root,anchor);window.addEventListener('nfl-diagnostics-updated',renderSoon);document.getElementById('currentBankroll')?.addEventListener('input',renderSoon);renderSoon();});
  window.NFL_PRODUCT_V2={refresh:renderSoon};
})();