(() => {
  const KEY='nflQolV3';
  const BETS='nflQolBetsV3';
  const DEFAULTS={favorites:[],excluded:[],locked:[],overrides:{},exposure:{maxPlayer:1,maxGame:2,noDuplicatePlayers:true,noTwoUnders:false}};
  const load=()=>{try{return {...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...DEFAULTS}}};
  let prefs=load();
  const save=()=>localStorage.setItem(KEY,JSON.stringify(prefs));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>(Number(n)||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
  const odds=n=>Number(n)>0?'+'+Math.round(n):String(Math.round(n));
  const implied=o=>o<0?(-o)/((-o)+100):100/(o+100);
  function games(){try{return state.games||[]}catch{return[]}}
  function gameOf(m){return games().find(g=>(g.markets||[]).includes(m))||games().find(g=>g.id===m.gameId)}
  function key(m,g=gameOf(m)){return [g?.id||m.gameId||'',m.marketKey||m.type,m.player||m.team||'',m.side||'',m.point??'',m.name||''].join('|')}
  function priceOkay(m,kind='general'){
    const p=Number(m.price); if(!Number.isFinite(p))return false;
    if(kind==='best') return p>=-250&&p<=200;
    if(kind==='builder') return p>=-300&&p<=220;
    if(kind==='lotto') return p>=-125&&p<=650;
    if(m.type==='td') return p>=-250&&p<=500;
    return p>=-450&&p<=600;
  }
  function eligible(m,kind='general'){
    const k=key(m); if(prefs.excluded.includes(k))return false;
    if(!priceOkay(m,kind))return false;
    const p=implied(Number(m.price)); if(p<=.08||p>=.90)return false;
    return true;
  }
  function overrideMarket(m){const o=prefs.overrides[key(m)];return o?{...m,point:o.point??m.point,price:Number(o.price),name:o.name||m.name,source:'Caesars override',_override:true}:m}
  function all(kind='general'){return games().flatMap(g=>(g.markets||[]).map(m=>({...overrideMarket(m),gameId:g.id,game:`${g.away} @ ${g.home}`,source:overrideMarket(m).source||g.dataSource||'Live'}))).filter(m=>eligible(m,kind))}
  function quality(m){let q=Number(m.sourceQuality)||60;const p=Number(m.price);if(p>=-160&&p<=120)q+=12;if(m.source==='Caesars'||m.source==='Caesars override')q+=8;if(m._override)q+=5;if(m.type==='td')q-=5;return Math.max(1,Math.min(100,q))}
  function grade(m){const q=quality(m),p=implied(Number(m.price))*100;let n=.58*q+.42*Math.min(75,p);if(m.source!=='Caesars'&&m.source!=='Caesars override')n=Math.min(n,82);return {score:n,letter:n>=82?'A':n>=76?'A-':n>=70?'B+':n>=64?'B':n>=58?'B-':'C',market:Math.round(q),script:Math.round(Math.min(90,55+(m.type==='h2h'?12:m.type==='spreads'?10:m.type==='totals'?8:m.player?7:0))),usage:m.player?Math.round(Math.min(88,50+(m.sourceQuality||60)*.35)):null}}
  function rank(list){return [...list].map(m=>({...m,_g:grade(m)})).sort((a,b)=>b._g.score-a._g.score)}
  function bestStraight(){return rank(all('best').filter(m=>!m.player))[0]||rank(all('best'))[0]||null}
  function bestProp(){return rank(all('best').filter(m=>m.player&&m.type!=='td'))[0]||rank(all('best').filter(m=>m.player))[0]||null}
  function buildTwo(){const pool=rank(all('builder'));const out=[];for(const m of pool){if(out.some(x=>x.gameId===m.gameId))continue;if(out.some(x=>x.player&&m.player&&x.player===m.player))continue;out.push(m);if(out.length===2)break}return out.length===2?out:[]}
  function bestSgp(){let best=[];for(const g of games()){const pool=rank((g.markets||[]).map(m=>({...overrideMarket(m),gameId:g.id,game:`${g.away} @ ${g.home}`,source:overrideMarket(m).source||g.dataSource||'Live'})).filter(m=>eligible(m,'builder')));const chosen=[];for(const m of pool){if(chosen.some(x=>x.player&&m.player&&x.player===m.player))continue;if(chosen.some(x=>x.type==='totals'&&m.type==='totals'))continue;chosen.push(m);if(chosen.length===3)break}if(chosen.length>=2&&chosen.reduce((s,x)=>s+x._g.score,0)>best.reduce((s,x)=>s+x._g.score,0))best=chosen}return best}
  function parlayOdds(legs){let d=1;for(const l of legs)d*=l.price>0?1+l.price/100:1+100/Math.abs(l.price);return d>=2?Math.round((d-1)*100):Math.round(-100/(d-1))}
  const toneFor=title=>title==='BEST BET'?'green':title==='BEST PLAYER PROP'?'blue':title==='BEST 2-LEG'?'purple':'gold';
  const iconFor=title=>title==='BEST BET'?'●':title==='BEST PLAYER PROP'?'◆':title==='BEST 2-LEG'?'⛓':'★';
  function card(title,m){const tone=toneFor(title);if(!m)return `<article class="qcard pass tone-${tone}"><div class="qtop"><span><i>${iconFor(title)}</i>${title}</span></div><h3>PASS</h3><p>No market cleared the price and quality filters.</p></article>`;const g=m._g||grade(m),k=key(m);return `<article class="qcard tone-${tone}" data-k="${esc(k)}"><div class="qtop"><span><i>${iconFor(title)}</i>${title}</span><b>${g.letter}</b></div><div class="qtitle"><h3>${esc(m.name)}</h3><strong>${odds(m.price)}</strong></div><p>${esc(m.game)} <small class="source-badge">${esc(m.source)}</small></p><div class="qmetrics"><span>Market <b>${g.market}</b></span>${g.usage!=null?`<span>Usage <b>${g.usage}</b></span>`:''}<span>Script <b>${g.script}</b></span></div><div class="qactions"><button data-act="fav">${prefs.favorites.includes(k)?'★':'☆'}</button><button data-act="lock">${prefs.locked.includes(k)?'🔒':'🔓'}</button><button data-act="why">Why</button><button data-act="override">Caesars</button><button data-act="exclude">×</button><button data-act="bet">Add bet</button></div></article>`}
  function miniParlay(title,legs){const tone=toneFor(title);if(!legs.length)return `<article class="qcard pass tone-${tone}"><div class="qtop"><span><i>${iconFor(title)}</i>${title}</span></div><h3>PASS</h3><p>No eligible combination.</p></article>`;const o=parlayOdds(legs),avg=legs.reduce((s,x)=>s+(x._g||grade(x)).score,0)/legs.length;return `<article class="qcard tone-${tone}"><div class="qtop"><span><i>${iconFor(title)}</i>${title}</span><b>${avg>=76?'A-':avg>=70?'B+':avg>=64?'B':'B-'}</b></div><div class="qtitle"><h3>${legs.length}-Leg Build</h3><strong>${odds(o)}</strong></div><ol>${legs.map(x=>`<li>${esc(x.name)} <small>${odds(x.price)}</small></li>`).join('')}</ol><div class="qactions"><button data-parlay='${esc(JSON.stringify(legs.map(x=>key(x))))}'>Add build to My Card</button></div></article>`}
  function myCard(){const fav=all().filter(m=>prefs.favorites.includes(key(m))||prefs.locked.includes(key(m)));if(!fav.length)return '';return `<section class="qpanel qmy-panel"><div class="qhead"><div><span>MY CARD</span><h2>Saved & Locked Legs</h2></div><button id="qClearCard">Clear</button></div><div class="qmy">${rank(fav).map(m=>`<div><b>${esc(m.name)}</b><span>${odds(m.price)} • ${esc(m.game)}</span></div>`).join('')}</div></section>`}
  function bets(){try{return JSON.parse(localStorage.getItem(BETS)||'[]')}catch{return[]}}
  function saveBets(a){localStorage.setItem(BETS,JSON.stringify(a))}
  function stats(a){const settled=a.filter(x=>['W','L','P'].includes(x.result));let pl=0,w=0,l=0,p=0,st=0;for(const b of settled){st+=b.stake;if(b.result==='W'){w++;pl+=b.odds>0?b.stake*b.odds/100:b.stake*100/Math.abs(b.odds)}else if(b.result==='L'){l++;pl-=b.stake}else p++}return {w,l,p,pl,roi:st?pl/st*100:0}}
  function tracker(){const a=bets(),s=stats(a),bank=Number(document.getElementById('currentBankroll')?.value)||0,unit=bank*.01;return `<section class="qpanel qtracker"><div class="qhead"><div><span>BET TRACKER</span><h2>Bet Tracker</h2></div><details class="tracker-menu"><summary>•••</summary><div><button id="qResetBank">Reset bankroll</button></div></details></div><div class="qstats"><div><small>Record</small><b>${s.w}-${s.l}-${s.p}</b></div><div><small>ROI</small><b>${s.roi.toFixed(1)}%</b></div><div><small>P/L</small><b>${money(s.pl)}</b></div><div class="bank-stat"><small>Bankroll</small><b>${money(bank)}</b><small>1 Unit ${money(unit)}</small></div></div><div class="qbetform"><input id="qSel" placeholder="Selection"><input id="qStake" type="number" min="0" step="0.01" placeholder="Stake"><input id="qOdds" type="number" placeholder="Odds"><button id="qAddBet">Add Bet</button></div><div class="qhistory">${a.slice().reverse().slice(0,12).map(b=>`<div data-id="${b.id}"><span><b>${esc(b.selection)}</b><small>${money(b.stake)} @ ${odds(b.odds)}</small></span><span><button data-r="W">W</button><button data-r="L">L</button><button data-r="P">Push</button>${b.result?`<em>${b.result}</em>`:''}</span></div>`).join('')||'<p class="qempty">No tracked bets yet.</p>'}</div></section>`}
  function settings(){const e=prefs.exposure;return `<details class="qpanel qdetails"><summary><span>⚙</span><div><b>Advanced & Technical</b><small>Data sources, API usage, exposure controls, and more</small></div></summary><div class="qsettings"><label>Max bets/player <input id="qMaxPlayer" type="number" min="1" max="4" value="${e.maxPlayer}"></label><label>Max legs/game <input id="qMaxGame" type="number" min="1" max="6" value="${e.maxGame}"></label><label><input id="qDup" type="checkbox" ${e.noDuplicatePlayers?'checked':''}> No duplicate players</label><label><input id="qUnders" type="checkbox" ${e.noTwoUnders?'checked':''}> No two unders from same game</label></div><div id="qTech"></div></details>`}
  function ensureRoots(){let top=document.getElementById('qolV3');if(!top){top=document.createElement('div');top.id='qolV3';document.querySelector('.topbar')?.insertAdjacentElement('afterend',top)}let bottom=document.getElementById('qolV3Bottom');if(!bottom){bottom=document.createElement('div');bottom.id='qolV3Bottom';document.querySelector('main')?.insertAdjacentElement('afterend',bottom)}return {top,bottom}}
  function render(){const {top,bottom}=ensureRoots(),straight=bestStraight(),prop=bestProp(),two=buildTwo(),sgp=bestSgp();top.innerHTML=`<section class="qpanel qhero"><div class="qhead"><div><span>TODAY'S CARD</span><h2>Today's Card</h2><p>Price-sane, live-market recommendations. Extreme prices are filtered out.</p></div><button id="qBuild">⚡ Build My Card</button></div><div class="qgrid">${card('BEST BET',straight)}${card('BEST PLAYER PROP',prop)}${miniParlay('BEST 2-LEG',two)}${miniParlay('BEST SGP',sgp)}</div></section>${myCard()}`;bottom.innerHTML=`${tracker()}${settings()}`;wire(document);decorateParlays();syncLegacy();window.dispatchEvent(new CustomEvent('nfl-qol-rendered'))}
  function syncLegacy(){document.querySelector('.hero')?.setAttribute('hidden','');document.querySelector('.api-usage-card')?.classList.add('qhidden-tech');document.querySelector('.source-status-card')?.classList.add('qhidden-tech');document.querySelector('.bankroll-card')?.classList.add('qhidden-bankroll');document.getElementById('riskBehavior')?.setAttribute('hidden','');}
  function findByKey(k){return all().find(m=>key(m)===k)}
  function toggle(arr,k){prefs[arr]=prefs[arr].includes(k)?prefs[arr].filter(x=>x!==k):[...prefs[arr],k];save();render()}
  function wire(root){root.onclick=e=>{const b=e.target.closest('button');if(!b)return;const c=b.closest('[data-k]'),k=c?.dataset.k,m=k?findByKey(k):null,act=b.dataset.act;if(act==='fav')return toggle('favorites',k);if(act==='lock')return toggle('locked',k);if(act==='exclude'){prefs.excluded=[...new Set([...prefs.excluded,k])];save();return render()}if(act==='why'&&m)return why(m);if(act==='override'&&m)return override(m);if(act==='bet'&&m)return addBet(m);if(b.id==='qClearCard'){prefs.favorites=[];prefs.locked=[];save();return render()}if(b.id==='qBuild'){document.querySelector('.mode-tabs')?.scrollIntoView({behavior:'smooth'});return}if(b.id==='qAddBet')return manualBet();if(b.id==='qResetBank')return document.getElementById('resetBankrollBtn')?.click();if(b.dataset.r)return settle(b.closest('[data-id]').dataset.id,b.dataset.r);if(b.dataset.parlay){for(const k2 of JSON.parse(b.dataset.parlay)){if(!prefs.favorites.includes(k2))prefs.favorites.push(k2)}save();return render()}};['qMaxPlayer','qMaxGame','qDup','qUnders'].forEach(id=>document.getElementById(id)?.addEventListener('change',saveExposure))}
  function saveExposure(){prefs.exposure={maxPlayer:Number(document.getElementById('qMaxPlayer')?.value)||1,maxGame:Number(document.getElementById('qMaxGame')?.value)||2,noDuplicatePlayers:!!document.getElementById('qDup')?.checked,noTwoUnders:!!document.getElementById('qUnders')?.checked};save()}
  function why(m){const g=grade(m),warnings=[];if(m.type==='td')warnings.push('Touchdowns are high variance.');if(Math.abs(m.price)>200)warnings.push('Price is outside the preferred value band.');if(m.source==='Kalshi')warnings.push('Kalshi price is an implied-market proxy, not your final Caesars line.');alert(`${m.name}\n\nGrade: ${g.letter}\nMarket: ${g.market}/100\n${g.usage!=null?'Usage: '+g.usage+'/100\n':''}Script: ${g.script}/100\n\nWhy: clean live market with acceptable price discipline and source quality.\nWhy not: ${warnings.join(' ')||'No major market-level warning detected.'}`)}
  function override(m){const p=prompt(`Caesars odds for ${m.name}:`,m.price);if(p==null)return;const n=Number(p);if(!Number.isFinite(n))return;const pt=prompt('Caesars line/threshold (leave blank to keep current):',m.point??'');prefs.overrides[key(m)]={price:n,point:pt===''?m.point:Number(pt)};save();render()}
  function addBet(m){const stake=Math.max(.01,(Number(document.getElementById('currentBankroll')?.value)||0)*.01);const a=bets();a.push({id:String(Date.now()),selection:m.name,stake:+stake.toFixed(2),odds:Number(m.price),source:m.source,grade:grade(m).letter,result:'',createdAt:new Date().toISOString()});saveBets(a);render()}
  function manualBet(){const selection=document.getElementById('qSel')?.value.trim(),stake=Number(document.getElementById('qStake')?.value),o=Number(document.getElementById('qOdds')?.value);if(!selection||!stake||!Number.isFinite(o))return;const a=bets();a.push({id:String(Date.now()),selection,stake,odds:o,result:'',createdAt:new Date().toISOString()});saveBets(a);render()}
  function settle(id,r){const a=bets(),b=a.find(x=>x.id===id);if(!b)return;b.result=r;saveBets(a);render()}
  function decorateParlays(){const cards=[...document.querySelectorAll('.parlay-card')];cards.forEach((c,i)=>{if(c.querySelector('.qoverlap'))return;const names=[...c.querySelectorAll('.leg-title,.leg strong')].map(x=>x.textContent.trim()).filter(Boolean);let max=0;for(let j=0;j<i;j++){const other=[...cards[j].querySelectorAll('.leg-title,.leg strong')].map(x=>x.textContent.trim());const overlap=names.filter(n=>other.includes(n)).length;max=Math.max(max,names.length?Math.round(overlap/names.length*100):0)}if(max){const s=document.createElement('span');s.className='qoverlap';s.textContent=`${max}% overlap`;c.querySelector('.card-footer')?.appendChild(s)}})}
  if(typeof window.marketQuality==='function'){const orig=window.marketQuality;window.marketQuality=function(m,v){if(!eligible(m,v==='long'?'lotto':'builder'))return -999;return orig(m,v)}}
  if(typeof window.buildMulti==='function'){const orig=window.buildMulti;window.buildMulti=function(count,risk,variant){const p=orig(count,risk,variant);if(!p?.legs)return p;const seenP=new Map(),seenG=new Map();p.legs=p.legs.filter(l=>{const pl=l.player||'',g=l.gameLabel||'';if(pl&&prefs.exposure.noDuplicatePlayers&&(seenP.get(pl)||0)>=prefs.exposure.maxPlayer)return false;if(g&&(seenG.get(g)||0)>=prefs.exposure.maxGame)return false;if(prefs.exposure.noTwoUnders&&l.side==='under'&&p.legs.some(x=>x!==l&&x.side==='under'&&x.gameLabel===g))return false;if(pl)seenP.set(pl,(seenP.get(pl)||0)+1);if(g)seenG.set(g,(seenG.get(g)||0)+1);return true});return p.legs.length===count?packageParlay(p.legs,variant,false):p}}
  document.addEventListener('DOMContentLoaded',()=>{render();document.getElementById('generateBtn')?.addEventListener('click',()=>setTimeout(()=>{decorateParlays();render()},120));window.addEventListener('nfl-diagnostics-updated',()=>setTimeout(render,80));document.getElementById('currentBankroll')?.addEventListener('input',()=>setTimeout(render,20));});
  window.NFL_QOL={refresh:render,prefs:()=>prefs,eligible,key};
})();