(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='betTerminalPrefsV1',LINES='betTerminalLinesV1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n)>0?'+'+Math.round(n):String(Math.round(n));
function markets(){const a=[];try{for(const g of state.games||[])for(const m of g.markets||[])a.push({...m,gameId:g.id,game:`${g.away} @ ${g.home}`,gameContext:g.context})}catch{}return a}
function key(m){return[m.gameId||'',m.marketKey||m.type,m.player||m.team||'',m.side||'',m.point??'',m.name||''].join('|')}
function find(k){return markets().find(m=>key(m)===k)}
function stats(m){const p=window.NFL_PROJECTIONS?.describe?.(m)||{},market=Number(p.marketP)||((m.price>0)?100/(m.price+100):Math.abs(m.price)/(Math.abs(m.price)+100)),model=Number(p.modelP)||Number(m.modelProbability)||market,edge=model-market,ev=Number(p.ev??m.modelEV)||0,conf=Number(p.confidence??m.modelConfidence??m.confidenceScore??m.confidence)||0;return{...p,market,model,edge,ev,conf}}
function metric(n){return Number.isFinite(n)?Math.round(n*100)+'%':'—'}
function lineMove(m){let h={};try{h=JSON.parse(localStorage.getItem(LINES)||'{}')}catch{}const k=key(m),cur={point:m.point,price:m.price,t:Date.now()},old=h[k];h[k]=cur;try{localStorage.setItem(LINES,JSON.stringify(h))}catch{}if(!old)return'';const dp=Number(cur.point)-Number(old.point);if(Number.isFinite(dp)&&Math.abs(dp)>=.5)return `<span class="move ${dp>0?'up':'down'}">Line ${old.point} → ${cur.point} ${dp>0?'▲':'▼'} ${Math.abs(dp)}</span>`;if(old.price!==cur.price)return `<span class="move">Price ${fmt(old.price)} → ${fmt(cur.price)}</span>`;return''}
function ticket(card){if(card.classList.contains('pass'))return;const m=find(card.dataset.k);if(!m||card.dataset.ticketed)return;card.dataset.ticketed='1';const s=stats(m),title=card.querySelector('.qtop span')?.textContent?.trim()||'RECOMMENDATION',q=window.NFL_SELECTIVITY?.valueScore?.(m,'balanced')??0;card.innerHTML=`<div class="ticket-kicker">${esc(title)}</div><div class="ticket-main"><div><h3>${esc(m.name)}</h3><p>${esc(m.game)}</p></div><strong>${fmt(m.price)}</strong></div><div class="model-strip"><span>MODEL <b>${metric(s.model)}</b></span><span>MARKET <b>${metric(s.market)}</b></span><span class="${s.edge>=.04?'positive':s.edge<0?'negative':''}">EDGE <b>${s.edge>=0?'+':''}${metric(s.edge)}</b></span><span>EV <b>${s.ev>=0?'+':''}${metric(s.ev)}</b></span><span>CONF <b>${Math.round(s.conf)||'—'}</b></span></div>${lineMove(m)}<div class="ticket-actions"><button data-use-builder="${esc(key(m))}">Use in Builder</button><button data-act="why">Why this bet</button></div>`}
function pass(card){if(!card.classList.contains('pass')||card.dataset.passdone)return;card.dataset.passdone='1';const pool=markets().map(m=>({m,s:stats(m)})).filter(x=>Number.isFinite(x.s.edge)).sort((a,b)=>b.s.edge-a.s.edge),best=pool[0];card.classList.add('pass-strip');card.innerHTML=`<b>NO BET QUALIFIES</b><span>${best?`Best available edge ${best.s.edge>=0?'+':''}${metric(best.s.edge)} · below model gate`:'No eligible live market'}</span>`}
function summary(){let bar=$('#cardSummary');if(!bar){bar=document.createElement('section');bar.id='cardSummary';bar.className='card-summary';const sw=$('.sport-switch');(sw||$('.topbar')).insertAdjacentElement('afterend',bar)}const xs=markets().map(m=>stats(m)),qualified=xs.filter(x=>x.edge>=.04&&x.conf>=76),best=xs.length?Math.max(...xs.map(x=>x.edge)):0;const status=$('#dataStatus')?.textContent||'',age=status.match(/updated\s+(\d+)m/i)?.[1];bar.innerHTML=`<span><b>TODAY</b></span><span><b>${qualified.length}</b> qualified</span><span>Best edge <b class="${best>=.04?'positive':''}">${best>=0?'+':''}${metric(best)}</b></span><span>Data <b class="${age>30?'warn':''}">${age?age+'m':'live'}</b></span>`}
function rejectPanel(){const d=$('.market-filter-details');if(!d||d.querySelector('.reject-list'))return;const box=document.createElement('div');box.className='reject-list';const xs=markets().map(m=>({m,s:stats(m)})).filter(x=>x.s.edge<.04).sort((a,b)=>b.s.edge-a.s.edge).slice(0,5);box.innerHTML='<div class="reject-title">Near misses</div>'+xs.map(x=>`<div class="reject-row"><span>${esc(x.m.name)}</span><small>${x.s.edge>=0?'+':''}${metric(x.s.edge)} edge · ${x.s.conf||'—'} conf</small></div>`).join('');d.querySelector('.market-box')?.append(box)}
function useBuilder(k){const m=find(k);if(!m)return;const game=$('#gameSelect');if(game&&m.gameId){game.value=m.gameId;game.dispatchEvent(new Event('change',{bubbles:true}))}const family=m.type;$$('#marketChips .chip').forEach(b=>{const on=b.dataset.market===family;b.classList.toggle('active',on);try{if(state?.selectedMarkets){on?state.selectedMarkets.add(b.dataset.market):state.selectedMarkets.delete(b.dataset.market)}}catch{}});$('.control-card')?.scrollIntoView({behavior:'smooth',block:'start'})}
function correlation(card){if(card.dataset.corrdone)return;const txt=card.querySelector('.correlation')?.textContent||'',n=parseInt((txt.match(/[+-]?\d+/)||[])[0]);if(!Number.isFinite(n))return;card.dataset.corrdone='1';const footer=card.querySelector('.card-footer');if(footer)footer.insertAdjacentHTML('beforeend',`<span class="corr-map ${n>=20?'strong':n>0?'medium':'conflict'}">${n>=20?'↗ Strong positive':n>0?'↗ Positive':'⚠ Weak/conflicting'} relationships</span>`)}
function variants(){const grid=$('#results');if(!grid)return;const all=[...grid.querySelectorAll(':scope > .parlay-card')],cards=all.slice(0,3);all.slice(3).forEach(c=>c.remove());let nav=$('#variantTabs');if(cards.length<2){nav?.remove();cards.forEach(c=>c.classList.remove('variant-hidden'));return}if(!nav){nav=document.createElement('div');nav.id='variantTabs';nav.className='variant-tabs';grid.before(nav)}nav.innerHTML='';let chosen=cards.findIndex(c=>/best balance|balanced parlay/i.test(c.textContent));if(chosen<0)chosen=0;cards.forEach((card,i)=>{correlation(card);const name=card.querySelector('.parlay-name')?.textContent||`Pick ${i+1}`,odds=card.querySelector('.odds')?.textContent||'';card.dataset.recIndex=i;const btn=document.createElement('button');btn.type='button';btn.dataset.recIndex=i;btn.innerHTML=`<span>${esc(name)}</span><b>${esc(odds)}</b>`;const select=()=>{cards.forEach((x,j)=>x.classList.toggle('variant-hidden',j!==i));[...nav.querySelectorAll('button')].forEach((x,j)=>{x.classList.toggle('active',j===i);x.setAttribute('aria-selected',j===i?'true':'false')})};btn.addEventListener('click',select);nav.append(btn);card.classList.toggle('variant-hidden',i!==chosen)});nav.querySelectorAll('button')[chosen]?.classList.add('active');nav.querySelectorAll('button').forEach((x,j)=>x.setAttribute('aria-selected',j===chosen?'true':'false'))}
function persist(){const save=()=>{const p={mode:state?.mode,game:$('#gameSelect')?.value,legs:$('#legsSelect')?.value,markets:[...state.selectedMarkets||[]],sport:$('.sport-switch button.active')?.dataset.sport};localStorage.setItem(STORE,JSON.stringify(p))};document.addEventListener('change',e=>{if(e.target.matches('#gameSelect,#legsSelect'))save()});document.addEventListener('click',e=>{if(e.target.closest('.chip,.mode-tabs button,.sport-switch button'))setTimeout(save,30);const u=e.target.closest('[data-use-builder]');if(u)useBuilder(u.dataset.useBuilder)});setTimeout(()=>{let p;try{p=JSON.parse(localStorage.getItem(STORE)||'null')}catch{}if(!p)return;if(p.legs&&$('#legsSelect')){$('#legsSelect').value=p.legs;$('#legsSelect').dispatchEvent(new Event('change',{bubbles:true}))}if(p.game&&$('#gameSelect')?.querySelector(`option[value="${CSS.escape(p.game)}"]`)){$('#gameSelect').value=p.game;$('#gameSelect').dispatchEvent(new Event('change',{bubbles:true}))}if(p.sport){const b=$(`.sport-switch button[data-sport="${p.sport}"]`);if(b&&!b.classList.contains('active'))b.click()}},900)}
function enhance(){const nfl=$('.sport-switch button.active')?.dataset.sport!=='mlb'&&$('.sport-switch button.active')?.dataset.sport!=='ncaaf'&&$('.sport-switch button.active')?.dataset.sport!=='ufc';const grid=$('#qolV3 .qgrid');if(nfl&&grid){[...grid.children].forEach(c=>c.classList.contains('pass')?pass(c):ticket(c));summary();rejectPanel()}else{$('#cardSummary')?.style.setProperty('display','none')}variants()}
let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,70)});function init(){obs.observe(document.body,{childList:true,subtree:true});persist();setTimeout(enhance,300)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();window.TERMINAL_QOL={enhance,useBuilder};})();