(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='betTerminalPrefsV1',LINES='betTerminalLinesV1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n)>0?'+'+Math.round(n):String(Math.round(n));
function markets(){const a=[];try{for(const g of state.games||[])for(const m of g.markets||[])a.push({...m,gameId:g.id,game:`${g.away} @ ${g.home}`,gameContext:g.context})}catch{}return a}
function key(m){return[m.gameId||'',m.marketKey||m.type,m.player||m.team||'',m.side||'',m.point??'',m.name||''].join('|')}
function find(k){return markets().find(m=>key(m)===k)}
function stats(m){const p=window.NFL_PROJECTIONS?.describe?.(m)||{},market=Number(p.marketP)||((m.price>0)?100/(m.price+100):Math.abs(m.price)/(Math.abs(m.price)+100)),model=Number(p.modelP)||Number(m.modelProbability)||market,edge=model-market,ev=Number(p.ev??m.modelEV)||0,conf=Number(p.confidence??m.modelConfidence??m.confidenceScore??m.confidence)||0;return{...p,market,model,edge,ev,conf}}
function metric(n){return Number.isFinite(n)?Math.round(n*100)+'%':'—'}
function lineMove(m){let h={};try{h=JSON.parse(localStorage.getItem(LINES)||'{}')}catch{}const k=key(m),cur={point:m.point,price:m.price,t:Date.now()},old=h[k];h[k]=cur;try{localStorage.setItem(LINES,JSON.stringify(h))}catch{}if(!old)return'';const dp=Number(cur.point)-Number(old.point);if(Number.isFinite(dp)&&Math.abs(dp)>=.5)return `<span class="move ${dp>0?'up':'down'}">Line ${old.point} → ${cur.point} ${dp>0?'▲':'▼'} ${Math.abs(dp)}</span>`;if(old.price!==cur.price)return `<span class="move">Price ${fmt(old.price)} → ${fmt(cur.price)}</span>`;return''}
function ticket(card){if(card.classList.contains('pass'))return;const m=find(card.dataset.k);if(!m||card.dataset.ticketed)return;card.dataset.ticketed='1';const s=stats(m),title=card.querySelector('.qtop span')?.textContent?.trim()||'RECOMMENDATION',q=window.NFL_SELECTIVITY?.valueScore?.(m,'balanced')??0;card.innerHTML=`<div class="ticket-kicker">${esc(title)}</div><div class="ticket-main"><div><h3>${esc(m.name)}</h3><p>${esc(m.game)}</p></div><strong>${fmt(m.price)}</strong></div><div class="model-strip"><span>MODEL <b>${metric(s.model)}</b></span><span>MARKET <b>${metric(s.market)}</b></span><span class="${s.edge>=.04?'positive':s.edge<0?'negative':''}">EDGE <b>${s.edge>=0?'+':''}${metric(s.edge)}</b></span><span>EV <b>${s.ev>=0?'+':''}${metric(s.ev)}</b></span><span>CONF <b>${Math.round(s.conf)||'—'}</b></span></div>${lineMove(m)}<div class="ticket-actions"><button data-use-builder="${esc(key(m))}">Use in Builder</button><button data-act="why">Why this bet</button></div>`}
function pass(card){if(!card.classList.contains('pass')||card.dataset.passdone)return;card.dataset.passdone='1';const pool=markets().map(m=>({m,s:stats(m)})).filter(x=>Number.isFinite(x.s.edge)).sort((a,b)=>b.s.edge-a.s.edge),best=pool[0];card.classList.add('pass-strip');card.innerHTML=`<b>NO BET QUALIFIES</b><span>${best?`Best available edge ${best.s.edge>=0?'+':''}${metric(best.s.edge)} · below model gate`:'No eligible live market'}</span>`}
function useBuilder(k){const m=find(k);if(!m)return;const game=$('#gameSelect');if(game&&m.gameId){game.value=m.gameId;game.dispatchEvent(new Event('change',{bubbles:true}))}const family=m.type;$$('#marketChips .chip').forEach(b=>{const on=b.dataset.market===family;b.classList.toggle('active',on);try{if(state?.selectedMarkets){on?state.selectedMarkets.add(b.dataset.market):state.selectedMarkets.delete(b.dataset.market)}}catch{}});$('.control-card')?.scrollIntoView({behavior:'smooth',block:'start'})}
function why(card){if(!card)return;let note=card.querySelector('.supporting-note');if(note){note.remove();return}const m=find(card.dataset.k);if(!m)return;const ctx=m.gameContext||{},bits=[];if(m.team){const form=ctx.recent_form?.[m.team];if(form?.available)bits.push(esc(m.team)+': '+form.wins+' wins in last '+form.games+' games, '+form.avg_points_for+' points scored/game')}const injury=m.contextSignals?.injury_status;if(m.player&&injury&&injury!=='none_reported')bits.push(esc(m.player)+' injury status: '+esc(injury));const weather=ctx.weather||{};if(weather.indoor===true)bits.push('Indoor venue');else if(Number.isFinite(+weather.wind_mph)&&weather.wind_mph!==null)bits.push('Wind: '+esc(weather.wind_mph)+' mph');note=document.createElement('div');note.className='supporting-note';note.innerHTML='<b>Supporting context · ESPN</b><br>'+(bits.length?bits.join('<br>'):'No independent matchup detail is available for this selection.');card.appendChild(note)}
function variants(){
 const grid=$('#results');if(!grid)return;
 const nfl=(window.__ACTIVE_SPORT||'nfl')==='nfl';
 const cards=[...grid.children].filter(x=>x.classList.contains('parlay-card'));
 const carousel=nfl&&cards.length>=2;
 grid.classList.toggle('nfl-carousel',carousel);
 grid.setAttribute('aria-label',carousel?'NFL parlay ideas. Swipe left or right for Conservative, Balanced and Lotto.':'Recommendations');
 cards.forEach(card=>card.classList.remove('variant-hidden'));
 const hint=$('#parlaySwipeHint');if(hint){hint.hidden=!carousel;if(carousel){
   if(!hint.querySelector('.carousel-position'))hint.innerHTML='<span class="carousel-instruction">Swipe parlays</span><span class="carousel-position" aria-live="polite"></span><span class="carousel-dots" role="group" aria-label="Parlay options"></span>';
   const dots=hint.querySelector('.carousel-dots');
   dots.replaceChildren(...cards.map((card,i)=>{const b=document.createElement('button');b.type='button';b.className='carousel-dot';b.setAttribute('aria-label','Show '+(card.querySelector('.parlay-name')?.textContent||'option '+(i+1)));b.addEventListener('click',()=>{const current=[...grid.children].filter(x=>x.classList.contains('parlay-card'))[i];if(!current)return;const left=current.getBoundingClientRect().left-grid.getBoundingClientRect().left+grid.scrollLeft;grid.scrollTo({left,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});return b}));
   const update=()=>{const current=[...grid.children].filter(x=>x.classList.contains('parlay-card'));if(!current.length)return;const active=current.reduce((best,card,i)=>Math.abs(card.getBoundingClientRect().left-grid.getBoundingClientRect().left)<Math.abs(current[best].getBoundingClientRect().left-grid.getBoundingClientRect().left)?i:best,0);const position=hint.querySelector('.carousel-position'),buttons=hint.querySelector('.carousel-dots')?.children;if(position)position.textContent=(active+1)+' of '+current.length;[...(buttons||[])].forEach((b,i)=>{b.classList.toggle('active',i===active);b.setAttribute('aria-current',i===active?'true':'false')})};
   if(!grid.dataset.positionListening){grid.dataset.positionListening='1';grid.addEventListener('scroll',()=>requestAnimationFrame(update),{passive:true})}requestAnimationFrame(update);
 }}
 $('#variantTabs')?.remove();
}
function persist(){const save=()=>{const p={mode:state?.mode,game:$('#gameSelect')?.value,legs:$('#legsSelect')?.value,markets:[...state.selectedMarkets||[]],sport:$('.sport-switch button.active')?.dataset.sport};localStorage.setItem(STORE,JSON.stringify(p))};document.addEventListener('change',e=>{if(e.target.matches('#gameSelect,#legsSelect'))save()});document.addEventListener('click',e=>{const whyButton=e.target.closest('[data-act="why"]');if(whyButton){why(whyButton.closest('.qcard'));return}if(e.target.closest('.chip,.mode-tabs button,.sport-switch button'))setTimeout(save,30);const u=e.target.closest('[data-use-builder]');if(u)useBuilder(u.dataset.useBuilder)});setTimeout(()=>{let p;try{p=JSON.parse(localStorage.getItem(STORE)||'null')}catch{}if(!p)return;if(p.legs&&$('#legsSelect')){$('#legsSelect').value=p.legs;$('#legsSelect').dispatchEvent(new Event('change',{bubbles:true}))}if(p.game&&$('#gameSelect')?.querySelector(`option[value="${CSS.escape(p.game)}"]`)){$('#gameSelect').value=p.game;$('#gameSelect').dispatchEvent(new Event('change',{bubbles:true}))}if(p.sport){const b=$(`.sport-switch button[data-sport="${p.sport}"]`);if(b&&!b.classList.contains('active'))b.click()}},900)}
function enhance(){const nfl=(window.__ACTIVE_SPORT||'nfl')==='nfl';const grid=$('#qolV3 .qgrid');if(nfl&&grid){[...grid.children].forEach(c=>c.classList.contains('pass')?pass(c):ticket(c));}variants()}
let timer;const obs=new MutationObserver(mutations=>{if(!mutations.some(m=>m.target?.closest?.('#qolV3 .qgrid,#results,#dataStatus')))return;clearTimeout(timer);timer=setTimeout(enhance,70)});function init(){obs.observe(document.body,{childList:true,subtree:true});persist();setTimeout(enhance,300)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();window.TERMINAL_QOL={enhance,useBuilder};})();
