const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function runtime(){const window={},ctx=vm.createContext({window,Date,document:{},localStorage:{getItem(){return null}}});for(const f of ['market-guards.js','pick-quality.js','bankroll-feed-core.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);return {window,ctx,Q:window.PICK_QUALITY,C:window.BANKROLL_FEED_CORE}}
function row(a,sport='nfl',id='one',hours=2){const at=new Date().toISOString(),market={ticker:id,kind:'moneyline',type:'h2h',name:'Team wins',label:'Team ML',game_id:id,game_time:new Date(Date.now()+hours*3600000).toISOString(),yes_ask:.6,probability:.6,price:-150,source:'Kalshi',quotedAt:at};a.Q.prepare(sport,[market],{},[],at);return {sport,market,forecast:{modelP:.73,coverage:.9},label:market.name,event:id}}
test('feed requires future events, fresh quotes and sufficient shared model evidence',()=>{const a=runtime(),r=row(a);assert.equal(a.C.eligible([r]).length,1);assert.equal(a.C.decision(r,{price:110,at:new Date().toISOString()}).ready,false);assert.equal(a.C.eligible([{...r,forecast:{modelP:.60,coverage:.1}}]).length,0);assert.equal(a.C.eligible([row(a,'nfl','started',-1)]).length,0);assert.equal(a.C.eligible([row(a,'nfl','far',200)]).length,0);r.market.quotedAt=new Date(Date.now()-31*60000).toISOString();assert.equal(a.C.eligible([r]).length,0)});
test('cross-sport feed deduplicates events, caps each sport and excludes saved/pass identities',()=>{const a=runtime(),rows=[];for(const s of a.C.sports)for(let n=0;n<5;n++)rows.push(row(a,s,s+n));rows.push({...rows[0],market:{...rows[0].market,ticker:'alternative'}});const result=a.C.eligible(rows);assert.equal(result.length,15);assert.equal(new Set(result.map(a.C.event)).size,15);assert.equal(a.C.eligible(rows,{sport:'nhl'}).length,3);assert.ok(a.C.eligible(rows,{excludedEvents:[a.C.event(rows[0])]}).every(r=>a.C.event(r)!==a.C.event(rows[0])));assert.ok(a.C.eligible(rows,{excluded:[a.C.id(result[0])]}).every(r=>a.C.id(r)!==a.C.id(result[0])));assert.equal(a.C.eligible([row(a,'nfl','later',48)],{date:'today'}).length,0)});
test('playable status requires independent validated evidence, participation and a fresh acceptable price',()=>{const a=runtime(),r=row(a),quality={pass:true,validated:true,conservativeP:.65,warnings:[]};a.Q.assess=()=>quality;const offer={price:-150,at:new Date().toISOString()};assert.equal(a.C.decision(r,offer).ready,true);assert.equal(a.C.decision(r,{...offer,price:-300}).ready,false);assert.equal(a.C.decision(r,{...offer,at:new Date(Date.now()-16*60000).toISOString()}).ready,false);quality.warnings=['Lineup unconfirmed'];assert.equal(a.C.decision(r,offer).ready,false);quality.warnings=[];r.forecast.marketAnchored=true;assert.equal(a.C.decision(r,offer).ready,false);assert.equal(a.C.decision(r,offer).minimum,null);assert.equal(a.C.decision(r).ready,false)});
test('minimum price rounds conservatively at positive and negative odds',()=>{const a=runtime();for(const p of [.4,.51,.6,.75]){const odds=a.C.minimumOdds(p);assert.ok(p*a.Q.decimal(odds)-1>=.02-1e-10);assert.ok(p*a.Q.decimal(odds-1)-1<.02+1e-10)}assert.equal(a.C.minimumOdds(NaN),null)});
test('horizontal swipes select actions while vertical scrolling and short drags do nothing',()=>{const {C}=runtime();assert.equal(C.gesture(90,15),'save');assert.equal(C.gesture(-90,15),'pass');assert.equal(C.gesture(90,120),null);assert.equal(C.gesture(30,0),null)});
test('paper results retain frozen prices and exclude voids from ROI',()=>{const {C}=runtime(),r={odds:150,status:'pending'};const won=C.paperResult(r,'won'),lost=C.paperResult({odds:-200},'lost'),voided=C.paperResult({odds:100},'void');assert.equal(won.profit,1.5);assert.equal(r.status,'pending');const summary=C.summary([won,lost,voided,r]);assert.equal(summary.profit,.5);assert.equal(summary.roi,.25);assert.equal(C.paperResult(won,'pending').profit,0);assert.equal(C.paperResult(r,'invalid'),null)});
function component(blocked=false){const a=runtime(),events={},root={innerHTML:'',setAttribute(){},addEventListener(k,fn){events[k]=fn},querySelector(){return null}},storage=new Map();a.window.__ACTIVE_SPORT='bankroll';a.window.__SPORT_TOKEN=1;a.window.NFL_MODEL_V3={evaluate:()=>({modelP:.73,coverage:.9})};a.window.setInterval=()=>{};const doc={createElement:()=>root,querySelector:()=>({prepend(){}}),addEventListener(){}};Object.assign(a.ctx,{document:doc,crypto:{randomUUID:()=>String(Math.random())},localStorage:{getItem:k=>storage.get(k),setItem(k,v){if(blocked)throw Error('blocked');storage.set(k,v)}},fetch:async()=>({ok:false})});vm.runInContext(fs.readFileSync('bankroll-feed.js','utf8'),a.ctx);return {...a,root,events,storage,feed:a.window.BANKROLL_FEED}}
test('unavailable feeds show an honest empty state; storage failure never creates a saved pick',async()=>{const a=component(true);await a.feed.refresh();assert.match(a.root.innerHTML,/No qualifying picks right now/);a.feed.act('review');assert.match(a.root.innerHTML,/Storage is unavailable/);assert.equal(a.feed.records().length,0)});
test('sport switching invalidates in-flight feed responses before mutating model context',async()=>{const a=component(),pending=[];a.ctx.fetch=()=>new Promise(resolve=>pending.push(resolve));let prepared=0;a.Q.prepare=()=>prepared++;const request=a.feed.refresh();a.window.__ACTIVE_SPORT='nhl';a.window.__SPORT_TOKEN++;for(const resolve of pending)resolve({ok:true,json:async()=>({updated_at:new Date().toISOString(),games:[]})});await request;assert.equal(prepared,0)});
test('save freezes the verified price, pass advances, undo restores and settlement is reversible',async()=>{const a=component(),at=new Date().toISOString(),games=[1,2].map(i=>({id:'g'+i,away:'Away',home:'Home',commence_time:new Date(Date.now()+3600000).toISOString(),markets:[{ticker:'p'+i,type:'h2h',name:'Home wins',source:'Kalshi',price:-150,marketProbability:.6}]}));a.ctx.fetch=async url=>({ok:url.includes('kalshi-nfl'),json:async()=>({updated_at:at,games})});a.window.CAESARS_COMPARE={register:()=> 'verified',lookup:token=>token==='verified'?{price:120,at}:null};await a.feed.refresh();assert.equal(a.feed.candidates().length,2);a.feed.act('save');assert.equal(a.feed.records()[0].odds,120);assert.equal(a.feed.records()[0].oddsSource,'Caesars');assert.equal(a.feed.candidates().length,1);a.feed.act('pass');assert.equal(a.feed.candidates().length,0);a.feed.act('undo');assert.equal(a.feed.candidates().length,1);a.feed.act('undo');assert.equal(a.feed.records().length,0);assert.equal(a.feed.candidates().length,2);a.feed.act('save');const record=a.feed.records()[0];a.events.click({target:{closest:sel=>sel==='[data-paper-result]'?{dataset:{paperId:record.id,paperResult:'won'}}:null}});assert.ok(Math.abs(a.feed.records()[0].profit-1.2)<1e-10);a.feed.act('undo');assert.equal(a.feed.records().length,1);assert.match(a.root.innerHTML,/Undo the result/)});
