const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const window={};
vm.runInNewContext(fs.readFileSync('market-guards.js','utf8'),{window,Date});
const {improveTypes}=window.MARKET_GUARDS;
const a={game_id:'A',kind:'moneyline',confidence:70,quality:80,positiveEV:true};
const b={game_id:'B',kind:'moneyline',confidence:72,quality:80,positiveEV:true};
const stronger={game_id:'A',kind:'total',confidence:75,quality:81,positiveEV:true};
const weaker={game_id:'B',kind:'spread',confidence:70,quality:90,positiveEV:true};
const unverified={game_id:'A',kind:'spread',confidence:85,quality:90,positiveEV:false};
const opts={confidence:m=>m.confidence,valid:(_legs,_i,old,next)=>next.quality>=old.quality&&(!old.positiveEV||next.positiveEV)};
const selected=improveTypes([a,b],[a,b,stronger,weaker,unverified],opts);
assert.equal(selected[0],stronger,'a verified, more confident total can replace a moneyline');
assert.equal(selected[1],b,'a weaker spread cannot replace a moneyline');
assert.equal(a.kind,'moneyline','the baseline is not mutated');
assert.equal(improveTypes([a],[unverified],opts)[0],a,'confidence cannot override the independent EV gate');
assert.equal(improveTypes([a],[{...stronger,game_id:'C'}],opts)[0],a,'no cross-game substitution');
console.log('Market variety gates passed');
