const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const {fit,build,calibrated}=require('../scripts/build_model_calibration');
const sample=(n,wins,offset=0)=>Array.from({length:n},(_,i)=>({id:String(i+offset),event:'Game '+(i+offset),eventTime:'2026-10-01T00:00:00Z',recordedAt:new Date(Date.UTC(2026,8,1+i+offset)).toISOString(),forecastType:'model',modelP:.8,rawModelP:.8,marketP:.6,result:i%5<wins?'win':'loss'}));
const rows=sample(60,3),rule=fit(rows);
assert.equal(rule.active,true,'adjustment must improve later results');
assert.ok(rule.adjustedBrier<rule.rawBrier);
assert.ok(calibrated(rows[0],rule.alpha,rule.bias)<.8);
assert.equal(fit(rows.slice(0,49)).active,false,'no early learning');
assert.deepEqual(fit([...rows,...sample(10,3,60)],rule).alpha,rule.alpha,'freeze parameters until 20 later events');
const misleading=[...sample(40,3),...sample(20,4,40)];
assert.equal(fit(misleading).active,false,'reject a fit that hurts later outcomes');
const duplicate=[...rows.slice(0,49),{...rows[0],id:'duplicate'}];
assert.equal(fit(duplicate).active,false,'same-event picks cannot create validation sample');
const grouped=build({records:[...rows.map(r=>({...r,sport:'mlb',marketGroup:'moneyline'})),...rows.slice(0,10).map(r=>({...r,id:'prop'+r.id,sport:'mlb',marketGroup:'player_prop'}))]});
assert.equal(grouped.sports.mlb.moneyline.active,true);
assert.equal(grouped.sports.mlb.player_prop.active,false,'market families need separate evidence');
const context={window:{MODEL_CALIBRATION_DATA:{sports:{mlb:{moneyline:rule}}}},localStorage:{getItem:()=>null},Math};
vm.runInNewContext(fs.readFileSync('model-calibration.js','utf8'),context);
vm.runInNewContext(fs.readFileSync('model-core.js','utf8'),context);
const bare=context.window.MODEL_CORE.evaluate({marketP:.6,signal:2,coverage:.5});
const adjusted=context.window.MODEL_CORE.evaluate({marketP:.6,signal:2,coverage:.5,sport:'mlb',marketGroup:'moneyline',calibrate:true});
const untouched=context.window.MODEL_CORE.evaluate({marketP:.6,signal:2,coverage:.5,sport:'mlb',marketGroup:'player_prop',calibrate:true});
assert.equal(adjusted.rawModelP,bare.modelP);
assert.notEqual(adjusted.modelP,bare.modelP);
assert.equal(untouched.modelP,bare.modelP);
console.log('Model calibration holdout and activation gates passed');
