const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const window={};vm.runInNewContext(fs.readFileSync('nfl-live-recovery.js','utf8'),{window,URL,Date,AbortController,setTimeout,clearTimeout});const api=window.NFL_LIVE_RECOVERY;
const now=Date.parse('2030-10-05T16:00:00Z'),time='2030-10-06T20:00:00Z';
const schedules=new Map([['2030-10-06',api.schedule({events:[{date:time,status:{type:{state:'pre',completed:false}},competitions:[{competitors:[{team:{abbreviation:'NO'}},{team:{abbreviation:'TB'}}]}]}]})]]);
function market(s,ticker,title,ask=.6,bid=.58){return {series:s,market:{ticker,event_ticker:s+'-30OCT06NOTB',title,status:'active',yes_ask_dollars:String(ask),yes_bid_dollars:String(bid)}}}
test('live recovery uses real quotes with schedule-verified future kickoff',()=>{const games=api.normalize([market('KXNFLGAME','KXNFLGAME-30OCT06NOTB-NO','New Orleans Saints')],schedules,now);assert.equal(games.length,1);assert.equal(games[0].commence_time,time);assert.equal(games[0].markets[0].price,-150);assert.equal(games[0].markets[0].quoteProbability,.6)});
test('unverified schedule, started games and unusable quotes never appear as fresh picks',()=>{const row=market('KXNFLGAME','KXNFLGAME-30OCT06NOTB-NO','Saints');assert.equal(api.normalize([row],new Map(),now).length,0);assert.equal(api.normalize([row],schedules,Date.parse(time)).length,0);row.market.yes_bid_dollars='0';assert.equal(api.normalize([row],schedules,now).length,0);assert.equal(api.quote({yes_ask_dollars:'1',yes_bid_dollars:'.9'}),null)});
test('totals and spreads retain both sides and distinguish nearby ALT thresholds',()=>{const games=api.normalize([market('KXNFLTOTAL','a','Over 44.5 points',.52,.48),market('KXNFLTOTAL','b','Over 41.5 points',.7,.68),market('KXNFLSPREAD','KXNFLSPREAD-30OCT06NOTB-NO3','New Orleans Saints wins by over 3.5 points',.52,.48),market('KXNFLSPREAD','KXNFLSPREAD-30OCT06NOTB-NO6','New Orleans Saints wins by over 6.5 points',.32,.28)],schedules,now);const ms=games[0].markets;assert.equal(ms.filter(m=>m.isAltLine).length,4);assert.ok(ms.some(m=>m.team==='Tampa Bay Buccaneers'&&m.point===3.5&&m.quoteSide==='no'));assert.ok(ms.some(m=>m.side==='under'&&m.point===44.5&&Math.abs(m.quoteProbability-.52)<1e-9))});
test('live prop identifiers preserve Caesars exclusions and alternate-yard labels',()=>{const games=api.normalize([market('KXNFLPASSATT','a','Example QB: 30+ passing attempts',.52,.48),market('KXNFLRSHYDS','b','Example RB: 50+ rushing yards',.52,.48),market('KXNFLRSHYDS','c','Example RB: 25+ rushing yards',.75,.72)],schedules,now);const ms=games[0].markets;assert.ok(ms.some(m=>m.marketKey==='player_pass_attempts'));assert.ok(ms.some(m=>m.marketKey==='player_rush_yds_alternate'&&m.point===24.5))});
