const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function runtime(blocked=false){let now=Date.now();const state=new Map();class Clock extends Date{constructor(...args){super(...(args.length?args:[now]))}static now(){return now}}
 const window={},ctx=vm.createContext({window,Date:Clock,console,localStorage:{getItem:k=>state.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('blocked');state.set(k,v)}}});
 for(const file of ['model-calibration.js','pick-quality.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
 return {Q:window.PICK_QUALITY,window,ctx,now:()=>now,advance:ms=>now+=ms};}
function fixture(r,patch={}){const m={ticker:'MATCH-45',type:'totals',marketKey:'totals',point:44.5,side:'over',name:'Over 44.5',price:100,marketProbability:.5,source:'Kalshi',game_status:'pre',...patch},g={id:'game',commence_time:new Date(r.now()+2*3600000).toISOString(),game_status:'pre',markets:[m]};r.Q.prepare('nfl',[m],{},[g],new Date(r.now()).toISOString());return {m,g,f:{modelP:.75,rawModelP:.75,coverage:.7,marketP:.5,uncertainty:.3}}}
test('all selections need independent coverage and edge beyond a named uncertainty buffer',()=>{const r=runtime(),{m,f}=fixture(r);assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.49}).pass,false);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.53}).pass,false);assert.equal(r.Q.assess('nfl',m,{...f,coverage:.1}).reason,'Independent projection too thin');assert.equal(r.Q.assess('nfl',m,{...f,modelP:.5}).reason,'Market-only estimate');assert.ok(r.Q.assess('nfl',m,f).conservativeP<f.modelP)});
test('manual Caesars odds affect value without rewriting reference prices',()=>{const r=runtime(),{m,g,f}=fixture(r);r.Q.record('nfl',m,{price:-400,point:44.5,eventTime:g.commence_time});const x=r.Q.assess('nfl',m,f);assert.equal(x.pass,false);assert.equal(x.quote.source,'Caesars manual');assert.equal(m.price,100);r.Q.record('nfl',m,{price:200,point:44.5,eventTime:g.commence_time});assert.equal(r.Q.assess('nfl',m,f).pass,true)});
test('exact selection, side and line matching survives builder copies but never spills into another pick',()=>{const r=runtime(),{m,g}=fixture(r);assert.throws(()=>r.Q.record('nfl',m,{price:120,point:45.5,eventTime:g.commence_time}),/Line differs/);r.Q.record('nfl',m,{price:120,point:44.5,eventTime:g.commence_time});assert.equal(r.Q.quote('nfl',{...m,gameId:g.id,kickoff:g.commence_time}).source,'Caesars manual');assert.equal(r.Q.quote('nfl',{...m,side:'under'}).source,'Kalshi');assert.equal(r.Q.quote('nfl',{...m,point:45.5}).source,'Kalshi')});
test('manual checks expire and started events always fail',()=>{const r=runtime(),{m,g,f}=fixture(r);r.Q.record('nfl',m,{price:120,point:44.5,eventTime:g.commence_time});r.advance(31*60000);assert.equal(r.Q.quote('nfl',m).source,'Kalshi');assert.equal(r.Q.assess('nfl',m,f).reason,'Quote older than 30 minutes');r.advance(2*3600000);assert.equal(r.Q.assess('nfl',m,f).reason,'Event already started')});
test('injury, roster and role checks cannot be bypassed by odds; attempts stay straight only',()=>{const r=runtime(),{m,g,f}=fixture(r,{player:'Player',_rosterVerified:true,type:'rushing',marketKey:'player_rush_attempts',contextSignals:{injury_status:'questionable'}});assert.equal(r.Q.assess('nfl',m,f).reason,'Confirm current injury status');r.Q.record('nfl',m,{price:100,point:44.5,eventTime:g.commence_time,participationConfirmed:true});assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,f,{parlay:true}).reason,'Caesars straight only');m.contextSignals.injury_status='out';assert.equal(r.Q.assess('nfl',m,f).reason,'Player unavailable');m.contextSignals.injury_status='none_reported';m._rosterVerified=false;assert.equal(r.Q.assess('nfl',m,f).reason,'Roster unverified')});
test('fresh reported NFL availability still needs stable playing time',()=>{const r=runtime(),{m,g,f}=fixture(r,{player:'Player',_rosterVerified:true,type:'rushing',marketKey:'player_rush_yds',contextSignals:{injury_status:'none_reported',injury_checked:true}});g.context={updated_at:new Date(r.now()).toISOString()};assert.equal(r.Q.assess('nfl',m,{...f,roleStability:.4}).reason,'Playing time uncertain');assert.equal(r.Q.assess('nfl',m,{...f,roleStability:.7}).pass,true)});
test('MLB, NHL and college require their current lineup or participation checks',()=>{const r=runtime(),start=new Date(r.now()+3600000).toISOString();for(const s of ['mlb','nhl','ncaaf']){const m={ticker:s,kind:'moneyline',label:'Team ML',game_id:'1',game_time:start,yes_ask:.5,probability:.5,game_status:'pre'},f={modelP:.8,coverage:.8,experimental:true};r.Q.prepare(s,[m],{},[],new Date(r.now()).toISOString());assert.equal(r.Q.assess(s,m,f).pass,false,s);r.Q.record(s,m,{price:100,point:null,eventTime:start,participationConfirmed:true});assert.equal(r.Q.assess(s,m,f).pass,true,s)}});
test('verified MLB starters and nine-person lineups can qualify without a manual check',()=>{const r=runtime(),m={ticker:'mlb',kind:'moneyline',game_id:'1',game_time:new Date(r.now()+3600000).toISOString(),yes_ask:.5,probability:.5},f={modelP:.8,coverage:.8};r.Q.prepare('mlb',[m],{games:[{gamePk:1,startersConfirmed:true,lineupsConfirmed:true}]},[],new Date(r.now()).toISOString());assert.equal(r.Q.assess('mlb',m,f).pass,true)});
test('SGP evaluation uses actual odds and dependence bounds, without correlation uplifts',()=>{const r=runtime(),{m,g,f}=fixture(r),entries=[{market:m,forecast:f},{market:{...m,ticker:'OTHER',point:45.5,game_time:g.commence_time},forecast:f}];const x=r.Q.checkBuild('nfl',entries,true,400);assert.ok(x.bounds.lower<.5);assert.ok(x.bounds.upper<.75);assert.equal(x.actionable,true);assert.equal(r.Q.checkBuild('nfl',entries,true,100).valueStatus,'Joint value unverified');assert.equal(r.Q.checkBuild('nfl',entries,true,-400).valueStatus,'Price fails even the upper bound');assert.equal(r.Q.checkBuild('nfl',entries,true).actionable,false)});
test('closing Caesars prices require the same line and a pregame near-start observation',()=>{const r=runtime(),{m,g}=fixture(r);const row=r.Q.record('nfl',m,{price:100,point:44.5,eventTime:g.commence_time});r.advance(110*60000);assert.throws(()=>r.Q.close(row.key,row.checkedAt,{price:-120,point:45.5,observedAt:new Date(r.now()).toISOString()}),/same line/);assert.throws(()=>r.Q.close(row.key,row.checkedAt,{price:-120,point:44.5,observedAt:new Date(r.now()-3600000).toISOString()}),/Closing observation/);const closed=r.Q.close(row.key,row.checkedAt,{price:-120,point:44.5,observedAt:new Date(r.now()).toISOString()});assert.ok(closed.clv>0);assert.equal(closed.odds,100);assert.throws(()=>r.Q.close(row.key,row.checkedAt,{result:'win'}),/after the event starts/);r.advance(20*60000);assert.equal(r.Q.close(row.key,row.checkedAt,{result:'win'}).returnPerUnit,1)});
test('invalid prices, missing starts and unavailable storage fail explicitly',()=>{const r=runtime(),{m,g}=fixture(r);assert.throws(()=>r.Q.record('nfl',m,{price:99,point:44.5,eventTime:g.commence_time}),/American odds/);assert.throws(()=>r.Q.record('ufc',{ticker:'unknown',kind:'moneyline'},{price:100}),/future start/);const b=runtime(true),x=fixture(b);assert.throws(()=>b.Q.record('nfl',x.m,{price:100,point:44.5,eventTime:x.g.commence_time}),/storage unavailable/);assert.equal(b.Q.ledger().length,0)});
test('calibration uses the market family and retains experimental labels',()=>{const r=runtime(),{m,f}=fixture(r);r.window.MODEL_CALIBRATION_DATA={sports:{nfl:{totals:{active:true,validationCount:20,alpha:.5,bias:0}}}};const x=r.Q.assess('nfl',m,f);assert.equal(x.modelP,.625);assert.equal(x.validated,true);const exp=r.Q.forecast('nfl',m,{...f,experimental:true});assert.equal(exp.experimental,true);assert.equal(exp.calibrationValidated,false);assert.equal(exp.modelP,.75)});
test('NFL builder packaging refuses a weak leg even when the script fits',()=>{const r=runtime(),{m,g}=fixture(r);m.modelProbability=.75;m.projectionCoverage=.7;const source=fs.readFileSync('app.js','utf8'),boundary=source.indexOf("$$('#marketChips .chip').forEach");Object.assign(r.ctx,{document:{querySelector(){return null},querySelectorAll(){return[]}},setTimeout(){},localStorage:{getItem(){return null}},impliedProbability:o=>o>0?100/(o+100):Math.abs(o)/(100+Math.abs(o))});vm.runInContext(source.slice(0,boundary),r.ctx);r.window.NFL_PARLAY_STATE.games=[g];r.Q.prepare('nfl',[m],{},[g],new Date(r.now()).toISOString());r.ctx.market=m;assert.ok(vm.runInContext("packageParlay([market],'balanced',false)",r.ctx));m.modelProbability=.51;assert.equal(vm.runInContext("packageParlay([market],'balanced',false)",r.ctx),null)});
test('Caesars line checks use signed spreads and equivalent count thresholds',()=>{const {Q}=runtime();assert.equal(Q.line({kind:'spread',title:'Alabama wins by over 4.5 points'}),-4.5);assert.equal(Q.line({kind:'spread',label:'Kings +1.5 Puck line',line:1.5,side:'no'}),1.5);assert.equal(Q.line({kind:'hits',label:'Player: 2+ hits'}),1.5);assert.equal(Q.line({marketKey:'player_rush_yds',point:49.5,name:'Player 50+ rushing yards'}),49.5);assert.equal(Q.checkBuild('nfl',[],true,400).pass,false)});
test('fresh genuine sportsbook quotes do not inherit an old snapshot timestamp',()=>{const r=runtime(),{m,f}=fixture(r);r.advance(31*60000);assert.equal(r.Q.assess('nfl',m,f).pass,false);m.quotedAt=new Date(r.now()).toISOString();m.source='Caesars';assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,f).quote.source,'Caesars')});
test('Caesars API compatibility tags actual bookmaker provenance without relabeling unrelated text',async()=>{const window={location:{href:'https://example.test/'},fetch:async url=>{assert.equal(new URL(url).searchParams.get('bookmakers'),'williamhill_us');return new Response(JSON.stringify({bookmakers:[{key:'williamhill_us',title:'Caesars',markets:[]},{key:'fanduel',title:'FanDuel',markets:[]}]}),{headers:{'content-type':'application/json'}})}};vm.runInNewContext(fs.readFileSync('sportsbook-caesars.js','utf8'),{window,URL,Response,Request,Headers,console});const data=await (await window.fetch('https://api.the-odds-api.com/v4/sports/nfl/odds')).json();assert.equal(data.bookmakers[0].dashboardBookSource,'Caesars');assert.equal(data.bookmakers[1].dashboardBookSource,undefined);assert.equal(data.bookmakers[1].title,'FanDuel')});
test('displayed Caesars prices and independent price estimates use the entered quotes',()=>{const r=runtime(),{m,g}=fixture(r);vm.runInContext(fs.readFileSync('market-guards.js','utf8'),r.ctx);m.game_id='1';const other={...m,ticker:'OTHER',game_id:'2',price:100};r.Q.record('nfl',m,{price:150,point:44.5,eventTime:g.commence_time});assert.equal(r.Q.quoteLabel('nfl',m),'Caesars +150');assert.equal(r.Q.estimateOdds('nfl',[m,other]),400);assert.equal(r.Q.estimateOdds('nfl',[m,{...other,game_id:'1'}]),null)});
