const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function runtime(blocked=false){let now=Date.now();const state=new Map();class Clock extends Date{constructor(...args){super(...(args.length?args:[now]))}static now(){return now}}
 const window={},ctx=vm.createContext({window,Date:Clock,console,localStorage:{getItem:k=>state.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('blocked');state.set(k,v)}}});
 for(const file of ['model-calibration.js','pick-quality.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
 return {Q:window.PICK_QUALITY,window,ctx,state,now:()=>now,advance:ms=>now+=ms};}
function fixture(r,patch={}){const m={ticker:'MATCH-45',type:'totals',marketKey:'totals',point:44.5,side:'over',name:'Over 44.5',price:100,marketProbability:.5,source:'Kalshi',game_status:'pre',...patch},g={id:'game',commence_time:new Date(r.now()+2*3600000).toISOString(),game_status:'pre',markets:[m]};r.Q.prepare('nfl',[m],{},[g],new Date(r.now()).toISOString());return {m,g,f:{modelP:.75,rawModelP:.75,coverage:.7,marketP:.5,uncertainty:.3}}}
test('all selections need independent coverage and edge beyond a named uncertainty buffer',()=>{const r=runtime(),{m,f}=fixture(r);assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.49}).pass,false);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.53}).pass,false);assert.equal(r.Q.assess('nfl',m,{...f,coverage:.1}).reason,'Independent projection too thin');assert.equal(r.Q.assess('nfl',m,{...f,modelP:.5}).reason,'Market-only estimate');assert.ok(r.Q.assess('nfl',m,f).conservativeP<f.modelP)});
test('delayed references never qualify as current value and started events always fail',()=>{const r=runtime(),{m,f}=fixture(r);r.advance(31*60000);assert.equal(r.Q.quote('nfl',m).source,'Kalshi');assert.equal(r.Q.assess('nfl',m,f).valueQualified,false);assert.match(r.Q.assess('nfl',m,f).warnings.join(' '),/Delayed reference/);r.advance(2*3600000);assert.equal(r.Q.assess('nfl',m,f).reason,'Event already started')});
test('injury, roster and role checks cannot be bypassed by odds; attempts stay straight only',()=>{const r=runtime(),{m,g,f}=fixture(r,{player:'Player',_rosterVerified:true,type:'rushing',marketKey:'player_rush_attempts',contextSignals:{injury_status:'questionable'}});assert.equal(r.Q.assess('nfl',m,f).reason,'Confirm current injury status');m.contextSignals={injury_status:'none_reported',injury_checked:true};g.context={updated_at:new Date(r.now()).toISOString()};f.roleStability=.7;assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,f,{parlay:true}).reason,'Caesars straight only');m.contextSignals.injury_status='out';assert.equal(r.Q.assess('nfl',m,f).reason,'Player unavailable');m.contextSignals.injury_status='none_reported';m._rosterVerified=false;assert.equal(r.Q.assess('nfl',m,f).reason,'Roster unverified')});
test('fresh reported NFL availability still needs stable playing time',()=>{const r=runtime(),{m,g,f}=fixture(r,{player:'Player',_rosterVerified:true,type:'rushing',marketKey:'player_rush_yds',contextSignals:{injury_status:'none_reported',injury_checked:true}});g.context={updated_at:new Date(r.now()).toISOString()};assert.equal(r.Q.assess('nfl',m,{...f,roleStability:.4}).reason,'Playing time uncertain');assert.equal(r.Q.assess('nfl',m,{...f,roleStability:.7}).pass,true)});
test('Missing lineup information produces labeled conditional suggestions rather than a permanent veto',()=>{const r=runtime(),start=new Date(r.now()+3600000).toISOString();for(const s of ['mlb','nhl','ncaaf']){const m={ticker:s,kind:'moneyline',label:'Team ML',game_id:'1',game_time:start,yes_ask:.5,probability:.5,game_status:'pre'},f={modelP:.8,coverage:.8,experimental:true};r.Q.prepare(s,[m],{},[],new Date(r.now()).toISOString());const x=r.Q.assess(s,m,f);assert.equal(x.pass,true,s);assert.equal(x.tier,'conditional');assert.equal(x.valueQualified,false);assert.ok(x.warnings.length);assert.equal(r.Q.record,undefined)}});
test('verified MLB starters and nine-person lineups can qualify without a manual check',()=>{const r=runtime(),m={ticker:'mlb',kind:'moneyline',game_id:'1',game_time:new Date(r.now()+3600000).toISOString(),yes_ask:.5,probability:.5},f={modelP:.8,coverage:.8};r.Q.prepare('mlb',[m],{games:[{gamePk:1,startersConfirmed:true,lineupsConfirmed:true}]},[],new Date(r.now()).toISOString());assert.equal(r.Q.assess('mlb',m,f).pass,true)});
test('SGP evaluation uses actual odds and dependence bounds, without correlation uplifts',()=>{const r=runtime(),{m,g,f}=fixture(r),entries=[{market:m,forecast:f},{market:{...m,ticker:'OTHER',point:45.5,game_time:g.commence_time},forecast:f}];const x=r.Q.checkBuild('nfl',entries,true,400);assert.ok(x.bounds.lower<.5);assert.ok(x.bounds.upper<.75);assert.equal(x.actionable,true);assert.equal(r.Q.checkBuild('nfl',entries,true,100).valueStatus,'Joint value unverified');assert.equal(r.Q.checkBuild('nfl',entries,true,-400).valueStatus,'Price fails even the upper bound');assert.equal(r.Q.checkBuild('nfl',entries,true).actionable,false)});
test('calibration uses the market family and retains experimental labels',()=>{const r=runtime(),{m,f}=fixture(r);r.window.MODEL_CALIBRATION_DATA={sports:{nfl:{totals:{active:true,validationCount:20,alpha:.5,bias:0}}}};const x=r.Q.assess('nfl',m,f);assert.equal(x.modelP,.625);assert.equal(x.validated,true);const exp=r.Q.forecast('nfl',m,{...f,experimental:true});assert.equal(exp.experimental,true);assert.equal(exp.calibrationValidated,false);assert.equal(exp.modelP,.75)});
test('NFL builder packaging refuses a weak leg even when the script fits',()=>{const r=runtime(),{m,g}=fixture(r);m.modelProbability=.75;m.projectionCoverage=.7;const source=fs.readFileSync('app.js','utf8'),boundary=source.indexOf("$$('#marketChips .chip').forEach");Object.assign(r.ctx,{document:{querySelector(){return null},querySelectorAll(){return[]}},setTimeout(){},localStorage:{getItem(){return null}},impliedProbability:o=>o>0?100/(o+100):Math.abs(o)/(100+Math.abs(o))});vm.runInContext(source.slice(0,boundary),r.ctx);r.window.NFL_PARLAY_STATE.games=[g];r.Q.prepare('nfl',[m],{},[g],new Date(r.now()).toISOString());r.ctx.market=m;assert.ok(vm.runInContext("packageParlay([market],'balanced',false)",r.ctx));m.modelProbability=.51;assert.equal(vm.runInContext("packageParlay([market],'balanced',false)",r.ctx),null)});
test('Market line checks use signed spreads and equivalent count thresholds',()=>{const {Q}=runtime();assert.equal(Q.line({kind:'spread',title:'Alabama wins by over 4.5 points'}),-4.5);assert.equal(Q.line({kind:'spread',label:'Kings +1.5 Puck line',line:1.5,side:'no'}),1.5);assert.equal(Q.line({kind:'hits',label:'Player: 2+ hits'}),1.5);assert.equal(Q.line({marketKey:'player_rush_yds',point:49.5,name:'Player 50+ rushing yards'}),49.5);assert.equal(Q.checkBuild('nfl',[],true,400).pass,false)});
test('fresh genuine sportsbook quotes do not inherit an old snapshot timestamp',()=>{const r=runtime(),{m,f}=fixture(r);r.advance(121*60000);m.game_time=new Date(r.now()+3600000).toISOString();assert.equal(r.Q.assess('nfl',m,f).pass,false);m.quotedAt=new Date(r.now()).toISOString();m.source='Caesars';assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.assess('nfl',m,f).quote.source,'Caesars')});
test('Caesars API compatibility tags actual bookmaker provenance without relabeling unrelated text',async()=>{const window={location:{href:'https://example.test/'},fetch:async url=>{assert.equal(new URL(url).searchParams.get('bookmakers'),'williamhill_us');return new Response(JSON.stringify({bookmakers:[{key:'williamhill_us',title:'Caesars',markets:[]},{key:'fanduel',title:'FanDuel',markets:[]}]}),{headers:{'content-type':'application/json'}})}};vm.runInNewContext(fs.readFileSync('sportsbook-caesars.js','utf8'),{window,URL,Response,Request,Headers,console});const data=await (await window.fetch('https://api.the-odds-api.com/v4/sports/nfl/odds')).json();assert.equal(data.bookmakers[0].dashboardBookSource,'Caesars');assert.equal(data.bookmakers[1].dashboardBookSource,undefined);assert.equal(data.bookmakers[1].title,'FanDuel')});
test('legacy manual prices cannot affect feed quotes, value or independent estimates',()=>{const r=runtime(),{m,g,f}=fixture(r);r.state.set('sportsPriceChecksV1',JSON.stringify([{key:r.Q.id('nfl',m),kind:'straight',book:'Caesars',line:44.5,odds:-400,checkedAt:new Date(r.now()).toISOString(),eventTime:g.commence_time,participationConfirmed:true}]));vm.runInContext(fs.readFileSync('pick-quality.js','utf8'),r.ctx);r.Q=r.window.PICK_QUALITY;r.Q.prepare('nfl',[m],{},[g],new Date(r.now()).toISOString());assert.equal(r.Q.quote('nfl',m).odds,100);assert.equal(r.Q.quoteLabel('nfl',m),'Kalshi +100');assert.equal(r.Q.assess('nfl',m,f).pass,true);assert.equal(r.Q.record,undefined);vm.runInContext(fs.readFileSync('market-guards.js','utf8'),r.ctx);m.game_id='1';const other={...m,ticker:'OTHER',game_id:'2'};assert.equal(r.Q.estimateOdds('nfl',[m,other]),300);assert.equal(r.Q.estimateOdds('nfl',[m,{...other,game_id:'1'}]),null);assert.equal(r.Q.checkBuild('nfl',[{market:m,forecast:f}],true).valueStatus,'Joint value unverified')});

test('market-anchored NFL suggestions do not pretend to establish independent value',()=>{const r=runtime(),{m,f}=fixture(r);m.price=-150;const x=r.Q.assess('nfl',m,{...f,modelP:.602,marketP:.60,coverage:.3,marketAnchored:true});assert.equal(x.pass,true);assert.equal(x.tier,'suggestion');assert.equal(x.valueQualified,false);assert.match(x.warnings.join(' '),/value unverified/);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.59,marketP:.6,coverage:.3,marketAnchored:true}).pass,false);assert.equal(r.Q.assess('nfl',m,{...f,modelP:.602,marketP:.6,coverage:.3}).pass,false)});
test('delayed suggestions expire after two hours and known unavailability still blocks them',()=>{const r=runtime(),{m,g,f}=fixture(r);g.commence_time=new Date(r.now()+4*3600000).toISOString();r.advance(121*60000);assert.equal(r.Q.assess('nfl',m,f).reason,'Quote older than 30 minutes');m.quotedAt=new Date(r.now()).toISOString();m.injury_status='out';assert.equal(r.Q.assess('nfl',m,f).reason,'Player unavailable')});
