const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function app(blocked=false){const nodes=new Map();let now=Date.now(),generated=0;class Clock extends Date{constructor(...a){super(...(a.length?a:[now]))}static now(){return now}}
 class Node{constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.dataset={};this.value='';this.checked=false;this.disabled=false;this.options=[];}set innerHTML(html){this.html=html;for(const match of html.matchAll(/<(\w+)[^>]*id="([^"]+)"/g)){const node=new Node(match[1]);node.id=match[2];nodes.set('#'+node.id,node)}}get innerHTML(){return this.html}append(...children){this.children.push(...children);if(this.tagName==='select'){this.options.push(...children);if(!this.value)this.value=children[0]?.value||''}}replaceChildren(){this.children=[];this.options=[];this.value=''}addEventListener(name,fn){this.listeners[name]=fn}dispatch(name){return this.listeners[name]?.({preventDefault(){},target:this})}insertAdjacentElement(_,child){this.children.push(child);nodes.set('#'+child.id,child)}setAttribute(k,v){this[k]=v}click(){}}
 nodes.set('#pickOfDay',new Node());const document={readyState:'loading',addEventListener(){},querySelector:s=>nodes.get(s)||null,createElement:tag=>new Node(tag)},window={__ACTIVE_SPORT:'nfl',generate(){generated++},NFL_MODEL_V3:{evaluate(){return{modelP:.75,rawModelP:.75,marketP:.5,coverage:.7,uncertainty:.3}}}};
 const store=new Map(),ctx=vm.createContext({document,window,Date:Clock,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('blocked');store.set(k,v)}},setTimeout(){},console,URL,Blob});
 for(const file of ['model-calibration.js','pick-quality.js','price-check-ui.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
 const start=new Date(now+2*3600000).toISOString(),markets=['Over 44.5','Under 44.5'].map((name,i)=>({ticker:'MATCH'+i,type:'totals',marketKey:'totals',point:44.5,side:i?'under':'over',name,price:100,marketProbability:.5})),game={id:'g',away:'Away',home:'Home',commence_time:start,markets};
 window.PICK_QUALITY.prepare('nfl',markets,{},[game],new Date(now).toISOString());window.PRICE_CHECK_UI.refresh();return{window,document,nodes,markets,game,advance:ms=>now+=ms,generated:()=>generated,Q:window.PICK_QUALITY,now:()=>now};}
test('manual Caesars form saves the exact selection, evaluates it, and regenerates',()=>{const a=app();assert.equal(a.nodes.get('#caesarsSelection').options.length,2);a.nodes.get('#caesarsOdds').value='150';a.nodes.get('#caesarsQuoteForm').dispatch('submit');assert.equal(a.Q.ledger().length,1);assert.equal(a.Q.ledger()[0].odds,150);assert.equal(a.Q.ledger()[0].modelP,.75);assert.equal(a.generated(),1);assert.match(a.nodes.get('#priceCheckMessage').textContent,/clears/);a.nodes.get('#caesarsSearch').value='Under';a.nodes.get('#caesarsSearch').dispatch('input');assert.equal(a.nodes.get('#caesarsSelection').options.length,1);assert.equal(a.nodes.get('#caesarsOdds').value,'')});
test('line mismatch and blocked storage show actionable errors without a saved quote',()=>{for(const blocked of [false,true]){const a=app(blocked);a.nodes.get('#caesarsOdds').value='150';if(!blocked)a.nodes.get('#caesarsLine').value='45.5';a.nodes.get('#caesarsQuoteForm').dispatch('submit');assert.equal(a.Q.ledger().length,0);assert.match(a.nodes.get('#priceCheckMessage').textContent,blocked?/storage unavailable/:/Line differs/)}});
test('saved-price form records same-line closing price and an observed result',()=>{const a=app();a.nodes.get('#caesarsOdds').value='100';a.nodes.get('#caesarsQuoteForm').dispatch('submit');a.advance(130*60000);a.nodes.get('#caesarsClosingOdds').value='-120';a.nodes.get('#caesarsClosingLine').value='44.5';a.nodes.get('#caesarsClosingTime').value=new Date(Date.parse(a.game.commence_time)-60000).toISOString();a.nodes.get('#caesarsResult').value='win';a.nodes.get('#caesarsHistoryForm').dispatch('submit');assert.equal(a.Q.ledger()[0].result,'win');assert.ok(a.Q.ledger()[0].clv>0);assert.equal(a.Q.ledger()[0].odds,100)});
test('SGP control saves actual combined odds and reports dependence uncertainty',()=>{const a=app(),card=a.document.createElement('article');a.window.PRICE_CHECK_UI.attach(card,'nfl',a.markets.map(m=>({market:m,forecast:{modelP:.75,coverage:.7,marketP:.5,uncertainty:.3}})),true);const detail=card.children[0],input=detail.children.find(n=>n.tagName==='input'),button=detail.children.find(n=>n.tagName==='button'),out=detail.children.at(-1);input.value='100';button.dispatch('click');assert.match(out.textContent,/Joint value unverified/);assert.equal(a.Q.ledger()[0].kind,'sgp');assert.equal(a.Q.ledger()[0].odds,100);assert.equal(a.Q.quote('nfl',a.markets[0]).source,'Reference feed')});
